import type { Article } from "../journal";

const article: Article = {
  slug: "aluminium-extrusion-tolerances-explained",
  title: "Aluminium extrusion tolerances: what they mean for a facade",
  seoTitle: "Aluminium Extrusion Tolerances Explained",
  description: "Aluminium profiles are never exactly their drawn size. How extrusion tolerances build up in windows and facades, and what to ask a fabricator.",
  excerpt: "Every aluminium profile is made within a permitted range, not to an exact size. Those small ranges add up across a frame and decide how well corners, seals and glass fit.",
  teaser: "Profiles are made within a range, not an exact size. The ranges add up.",
  topic: "Elements",
  date: "2026-10-08",
  hero: "extol-hero",
  card: "extol-card",
  og: "/og/casement-windows.jpg",
  terms: ["extrusion", "mitre-joint", "corner-crimping"],
  systems: ["casement-windows", "sliding-windows-doors"],
  faq: [
    {
      question: "What are aluminium extrusion tolerances?",
      answer: "They are the permitted variations in a profile's dimensions, shape and straightness during manufacture. No extrusion is exactly the drawn size, so standards and the profile supplier set an allowed range. Fabricators and designers must work within that range when cutting, joining and glazing.",
    },
    {
      question: "Why do window corners sometimes have gaps?",
      answer: "Corner gaps can come from profile variation, inaccurate cutting angles, worn tooling or poor assembly pressure. Small differences in the two profiles that meet add up at the joint. Good fabrication checks cut angles and uses sound crimping or cleating so the mitre closes cleanly.",
    },
    {
      question: "Do tolerances affect how well a window seals?",
      answer: "Yes. Gaskets and seals depend on the gap between parts staying within a designed range. If profiles or assembly vary too much, a gasket may be too loose or too tight, which can affect air and water performance. This is why tolerances matter beyond appearance.",
    },
    {
      question: "How do I check tolerances on a sample window?",
      answer: "Ask the fabricator to show the sample against the approved drawing and state which tolerance class applies. Look at corner closure, visible gaps between sashes and frames, flatness and straightness. A facade consultant can also review measurement records for the key dimensions on the sample.",
    },
  ],
  body: [
    { t: "p", x: "A drawing shows an aluminium window frame as a clean set of exact lines. The real frame is made of profiles that were pushed through a die, cooled, stretched, cut and finished, and none of those steps is perfect. Each profile ends up slightly different from its drawn shape, within a range that the manufacturer and the standards allow. That range is called a tolerance, and understanding it explains many of the small defects that make a good window look careless." },
    { t: "h2", x: "Where the variation comes from" },
    { t: "p", x: "An {{extrusion|extrusion}} is made by forcing heated aluminium through a shaped steel die. The die wears with use, the metal temperature and speed change a little during a run, and the profile cools and shrinks as it leaves the press. Long lengths are then straightened by stretching. Each of these steps leaves a small variation in wall thickness, overall width, angle and straightness, even when the process is well controlled." },
    { t: "p", x: "Finishing adds more. Anodising or coating adds a thin layer to every surface, which slightly changes dimensions and must be allowed for in the fit of parts that slide or clip together. A sloppy design assumes the bare metal size. A careful design allows for the finish, and the fabricator checks the finished profile before assembling it, not only the raw bar from the press." },
    { t: "h2", x: "Which tolerances matter on a facade" },
    { t: "p", x: "Not every dimension is equally important. A decorative outer face may tolerate a larger variation than the surfaces that hold a gasket or locate a glass edge. Standards and supplier catalogues describe permitted variation in several ways, and the project specification should state which classes apply to critical dimensions. The usual headings are listed below." },
    { t: "ul", items: [
      "Dimensional tolerance: the permitted variation in width, depth and wall thickness.",
      "Straightness: how far a length may bow or sweep along its axis.",
      "Twist: how much the profile may rotate along its length.",
      "Angle: the accuracy of corners and the faces that meet at a joint.",
      "Flatness: how level a broad face is across its width.",
    ] },
    { t: "p", x: "The specification should not simply say that tolerances must be tight. It should name the standard or class used, because a tight tolerance costs more and not every dimension needs it. A good specifier chooses precision where it affects sealing, sliding and glazing, and accepts normal variation where it does not." },
    { t: "img", id: "extol-1", cap: "Small differences in each profile add together where parts meet, which is why tolerances matter more at joints than on straight lengths." },
    { t: "h2", x: "How small errors add up at the corners" },
    { t: "p", x: "A corner is where two profiles meet, each with its own variation. In a {{mitre-joint|mitre joint}}, both pieces are cut at an angle and brought together, and a small error in the cutting angle or the profile shape shows up as a visible gap or a step between the faces. Corners are usually secured by {{corner-crimping|corner crimping}} or cleating, where a pressed key or an inserted piece pulls the joint tight. If the mitre does not close, the crimp can only hold a poor joint, not repair it." },
    { t: "p", x: "This build-up is called tolerance stacking. A frame made of four profiles, two glazing beads, a gasket and a sash has many dimensions, each with its own permitted variation. In the worst case, they all drift the same way. A designer who accepts that risk must leave enough clearance or adjustment in the system. A fabricator who ignores it will find the sash tight in one corner and loose in another." },
    { t: "h2", x: "Why tolerances affect weather performance" },
    { t: "p", x: "A {{gasket|gasket}} depends on a predictable gap. If the gap is too small, the gasket is overcompressed, may be hard to close and can wear quickly. If the gap is too large, it does not seal. Sliding windows have the same sensitivity: the clearance between sash and track determines how smooth the movement is and how well weather seals engage. Small errors in the profiles therefore affect air leakage and water performance, not just appearance." },
    { t: "p", x: "This is also the reason that tests of a sample describe the sample, not every window made afterwards. A good fabricator keeps the same profile quality and assembly method across the order. A test or a mock-up proves that a design can work. Consistent quality control proves that the production windows match it. Our guide to {{/journal/window-drainage-and-weep-holes|window drainage and weep holes}} shows why those small gaps matter for water." },
    { t: "h2", x: "Fabrication and quality control in the workshop" },
    { t: "p", x: "Good fabrication starts with incoming checks: confirm the profile type and finish, inspect for dents and bends, and measure key dimensions on a sample from each batch. Cutting then needs well-maintained saws, correct angles and fixtures that hold the profile without distorting it. Machining of drainage slots, lock holes and notches should be done with templates or CNC programmes, so each frame is the same." },
    { t: "ol", items: [
      "Check profile identity, finish and visible damage on delivery.",
      "Measure critical dimensions on a sample from the batch.",
      "Cut at the correct angle on a calibrated saw and test the first piece.",
      "Machine slots and holes from templates or a programme.",
      "Assemble the corners, then check diagonals and corner closure.",
      "Fit gaskets and hardware, and test movement before packing.",
    ] },
    { t: "p", x: "Checking the diagonals of a frame is a simple way to see squareness. If the two diagonals differ beyond the allowed amount, the frame is out of square and will be hard to glaze or operate. Records of these checks can be sent with each delivery, which gives the site team something to refer to." },
    { t: "h2", x: "Tolerances on site: the wall is not exact either" },
    { t: "p", x: "The aluminium frame is only half of the story. The opening in the wall, or the line of the slab edge for a curtain wall, also varies. A frame that is made to a tight tolerance must still fit into a structure that was built to a looser one. This is why a perimeter gap is left around the frame and filled with a sealant joint or other flexible closure, and why adjustable fixings are used." },
    { t: "p", x: "Survey the opening before final fabrication where possible, and agree who takes responsibility for out-of-tolerance openings. The relevant approach is explained in {{/journal/reading-facade-shop-drawings|reading facade shop drawings}}, where the stated clearances and adjustments show how much variation the design is meant to absorb. A site team should not force a frame into an opening that is too small, nor pack it with unplanned shims." },
    { t: "h2", x: "Straightness and how it shows on a long elevation" },
    { t: "p", x: "A slight bow in one mullion is hard to see on its own. Repeated across a long row of frames, with light raking across the surface, it shows up as a wavy line and makes the joints look uneven. Straightness matters more on long members, on dark finishes that show reflections, and on elevations viewed at a low angle. If the building has such a face, ask for the straightness requirement to be stated and checked on delivery." },
    { t: "p", x: "Handling can undo good manufacture. Profiles that are stacked without support, strapped too tightly or left in the sun can bend or mark. Protective film should stay on until the frame is installed and the surrounding trades have finished. A store that keeps profiles flat and supported is a good sign of a careful workshop." },
    { t: "h2", x: "Reading a sample against the drawing" },
    { t: "p", x: "A sample window is the best chance to see tolerances in practice. Place it beside the approved drawing and check the visible gaps at each corner, the way the sash sits in the frame, and the evenness of the sightlines. Open and close it several times and listen for rubbing. Ask the fabricator to explain any visible step or gap and say whether it is within the stated tolerance or needs to be corrected." },
    { t: "p", x: "Keep a record of what was agreed, with photographs and measurements, so production units can be compared with the approved sample. A written acceptance standard avoids arguments later, because both sides know what was approved. It is also useful to agree in advance who decides in a borderline case, and how a rejected unit will be corrected or replaced." },
    { t: "h2", x: "Questions to ask a fabricator" },
    { t: "ul", items: [
      "Which standard or tolerance class applies to the profiles, and who supplies them?",
      "How is the cutting angle checked, and how often is the saw calibrated?",
      "What corner method is used, and how is closure checked?",
      "How are diagonals and flatness measured, and are records kept?",
      "What clearance and adjustment does the design allow on site?",
    ] },
    { t: "p", x: "Tolerances are rarely a headline in a quotation, but they are among the best predictors of how a window will look and perform after a few years of use. A fabricator who can answer these questions plainly, and show measurement records, is usually one who has a controlled process." },
    { t: "note", x: "This guidance is general. Tolerance classes, standards and acceptance criteria are confirmed for each project with the facade consultant and the profile supplier." },
  ],
};

export default article;
