import type { Article } from "../journal";

const article: Article = {
  slug: "double-skin-facades-explained",
  title: "Double-skin facades explained",
  seoTitle: "Double-Skin Facades Explained",
  description: "A double-skin facade adds a second glass layer and a ventilated cavity. See how it works, where it helps, and the cost, upkeep and fire questions.",
  excerpt: "A double-skin facade wraps a building in two layers of glass with a cavity between. It can suit some projects, but it adds complexity that must be justified.",
  teaser: "Two layers, one cavity: where a double skin helps and where it does not.",
  topic: "Curtain wall",
  date: "2026-10-08",
  hero: "dsf-hero",
  card: "dsf-card",
  og: "/og/curtain-wall.jpg",
  terms: ["curtain-wall", "ventilated-cavity", "solar-heat-gain"],
  systems: ["curtain-wall"],
  faq: [
    { question: "What is a double-skin facade?", answer: "A double-skin facade has two layers of glazing separated by an air cavity, usually deep enough to hold blinds or allow access. The cavity can be ventilated to the outside or to the building, and the arrangement is chosen to manage heat, noise and wind." },
    { question: "Is a double-skin facade worth the cost?", answer: "It depends on the site and the brief. Noise, wind at height and solar control can justify it, but it adds cost, maintenance and design effort. A facade consultant should compare it with a good single-skin curtain wall using your actual climate and building use." },
    { question: "Does a double-skin facade reduce cooling load?", answer: "It can reduce solar heat reaching the occupied space when the cavity and shading are designed well, but results depend on climate, orientation, ventilation strategy and operation. A poor design can trap heat, so energy performance should be modelled rather than assumed." },
    { question: "How is the cavity of a double-skin facade cleaned?", answer: "Cavities are designed with access, such as walkways, hatches or removable panels, so both inner and outer glass can be cleaned and the blinds serviced. Access must be planned from the start because retrofitting it later is difficult and costly." },
  ],
  body: [
    { t: "p", x: "A double-skin facade looks simple in a diagram: two layers of glass with air between. In practice it is one of the most demanding envelope systems, and it is easy to choose for the wrong reasons. It is sometimes treated as a badge of sustainability when its real value is narrower. This article explains how it works, where it helps and what it asks of the people who design, build and maintain it." },
    { t: "h2", x: "What a double skin is" },
    { t: "p", x: "A double-skin facade places a second layer of glazing in front of the main enclosure, leaving a cavity between them. The inner layer is usually an insulating, airtight {{curtain-wall|curtain wall}} or window wall. The outer layer is a single or laminated glass screen that shields it. The cavity is often wide enough to hold blinds and, in some designs, a walkway for access." },
    { t: "p", x: "The point is to create a buffer zone. The outer skin takes wind and rain and cuts noise. The cavity can carry shading and, depending on the design, moving air that carries away heat. The inner skin does the work of keeping the building weather-tight. Each layer has a different job, and the design depends on keeping those jobs separate." },
    { t: "h2", x: "The common cavity types" },
    { t: "p", x: "Designers describe double skins by how the cavity is divided and ventilated. A box-window arrangement divides the cavity into small units, often one per window module, so air in one box does not rise to the next. A corridor type runs the cavity along a whole floor. A shaft type connects boxes into a vertical stack. A multi-storey type is a continuous cavity over several floors." },
    { t: "p", x: "The more continuous the cavity, the more it behaves like a chimney, and the more important fire, smoke and sound transfer become. Smaller separated cavities are easier to control but need more joints and more components. Neither type is inherently better. The choice follows the building height, the climate, the noise level and the maintenance plan." },
    { t: "h2", x: "How ventilation works" },
    { t: "p", x: "A {{ventilated-cavity|ventilated cavity}} lets air move through the space between the skins. In a naturally ventilated design, openings at the bottom and top allow warm air to rise and leave, carrying away heat that the sun puts into the cavity. In a mechanically assisted design, fans help. Some designs close the cavity to act as a buffer in cool weather." },
    { t: "p", x: "Climate decides whether any of this helps. In a cold region the cavity can act as a warm layer. In a hot, humid or dusty region, ventilating a cavity with outdoor air brings in heat, moisture and dust, and a poorly planned cavity can become hotter than the room. Treat any claim about a double skin as a question for modelling in your climate, not as a general benefit." },
    { t: "img", id: "dsf-1", cap: "The cavity is a working layer: air, shading and access are designed together, not added afterwards." },
    { t: "h2", x: "Heat, shading and glare" },
    { t: "p", x: "Blinds or louvres sit inside the cavity, protected from weather and wind. This lets them stay in place and work more reliably than exposed shading on a high tower. Because heat absorbed by the blind is released into the cavity rather than the room, the design can reduce {{solar-heat-gain|solar heat gain}} on the occupied side. The effect depends on how well the cavity air is moved or released." },
    { t: "p", x: "Glass choice still matters. The outer skin and the inner skin each carry coatings and build-ups that change light, colour and heat. Read {{/journal/choosing-facade-glass|choosing facade glass}} for the basics, then ask the consultant to test combinations on a sample. Reflections and colour can look different once two layers sit in front of each other." },
    { t: "h2", x: "Wind, noise and comfort at height" },
    { t: "p", x: "On tall buildings, wind speeds make opening windows difficult and noisy. An outer skin shelters the inner windows, so they can sometimes be opened for fresh air when they otherwise could not. The outer screen also reduces traffic and aircraft noise reaching the inner layer, provided its openings are arranged to limit direct sound paths into the cavity." },
    { t: "p", x: "Those benefits belong to specific briefs: a noisy city site, a high-rise with strong winds, or a building where natural ventilation is a design aim. If the site is quiet and the building is mechanically air-conditioned, a good single-skin curtain wall with external shading may deliver what is needed with less complexity. The question to ask is which problem the second layer solves." },
    { t: "h2", x: "Fire, smoke and safety" },
    { t: "p", x: "A cavity that runs across floors can carry smoke and fire between levels unless it is designed with barriers, compartments and approved details. This is a major reason that many double-skin designs divide the cavity at each floor or in separate boxes. Fire strategy for a double skin should be agreed with the approving authority early." },
    { t: "p", x: "Safety also includes falling glass, access hazards and cleaning risks. The outer skin may be laminated or toughened depending on the position, and the access walkways must follow the applicable local code. Ask the consultant to show how fire, smoke, glass breakage and maintenance access are handled together in one set of details." },
    { t: "h2", x: "Cost, weight and maintenance" },
    { t: "p", x: "A double skin has roughly two facades to build, support and maintain. It adds structure for the outer layer, cavity floors or walkways, extra glass to clean and moving parts such as vents and blinds. The inner {{curtain-wall|curtain wall}} still has to meet the performance of any envelope. The extra layer does not remove that responsibility, and it should never be treated as a substitute for a sound inner wall. If the outer skin were removed, the building should still be weather-tight, which is a useful test of whether the layers have clear and separate jobs." },
    { t: "p", x: "Maintenance is where many projects are surprised. Cavities collect dust, insects and condensation if drainage and sealing are poor. Blinds and actuators need servicing, and cleaning the inside faces of both skins needs planned access. Include a maintenance strategy and its budget in the decision, along with the guidance in the {{/journal/facade-maintenance-checklist|facade maintenance checklist}}." },
    { t: "h2", x: "Design and coordination across trades" },
    { t: "p", x: "A double skin touches almost every discipline: the structure that carries the outer layer, the fire strategy, the mechanical ventilation, the blinds and controls, the cleaning method and the glass. The facade consultant usually coordinates them, but each party needs to see the same drawings and the same assumptions. Gaps between trades often show up as cavity leaks, noise or heat that nobody planned." },
    { t: "p", x: "Early decisions are hard to reverse. The cavity depth, the position of vents and the structure of the outer skin set the geometry of the whole wall. Agree them before the glass and the inner frame are designed in detail. Ask the manufacturer to show how each connection is made, how tolerances are absorbed and how a failed pane in either skin would be replaced from the cavity or from outside." },
    { t: "p", x: "Test early, too. A full-scale bay lets the team judge the cavity width, the blinds, the access hatches and the appearance together. Problems that are obvious in a mock-up, such as an awkward hatch or a reflection that shows the cavity structure, cost little to change at that stage and a great deal after installation. Record what the mock-up showed, and carry each correction into the drawings for the whole building, so the lesson is learned once and applied everywhere." },
    { t: "h2", x: "When to choose it, and what to ask" },
    { t: "ul", items: [
      "Which problem does the second skin solve: noise, wind, solar control or natural ventilation?",
      "Has the performance been modelled for this climate and orientation?",
      "How is the cavity divided, ventilated and kept clean?",
      "How are fire and smoke controlled between floors?",
      "How are both skins and the blinds accessed for cleaning and repair?",
      "Is the added cost and weight justified against a well-designed single skin?",
    ] },
    { t: "p", x: "Start with the inner wall and treat the outer skin as a decision to be earned. If the answers are clear, a double skin can be a good solution. If they are not, a conventional {{/systems/curtain-wall|curtain wall}} with external shading is usually simpler to build and maintain. Build a full-scale {{mock-up|mock-up}} of at least one bay with both skins, so the team can see the cavity, access and finish." },
    { t: "note", x: "This guidance is general. Cavity type, ventilation, fire strategy and performance are confirmed per project with the facade consultant and the approving authority." },
  ],
};

export default article;
