import type { Article } from "../journal";

const article: Article = {
  slug: "facade-design-timeline-concept-to-handover",
  title: "A facade project timeline: from concept to handover",
  seoTitle: "Facade Project Timeline",
  description: "The stages of a facade project in order: concept, specification, shop drawings, mock-up, fabrication, installation and handover, and what each needs.",
  excerpt: "A facade is designed, approved, made and installed in a fixed sequence. Knowing the order, and what each stage needs from you, prevents most delays.",
  teaser: "The stages of a facade project, and what each one needs from you.",
  topic: "Enquiries",
  date: "2026-10-08",
  hero: "timeline-hero",
  card: "timeline-card",
  og: "/og/curtain-wall.jpg",
  terms: ["shop-drawings", "mock-up", "facade-consultant"],
  systems: ["curtain-wall"],
  faq: [
    {
      question: "How long does a facade project take from design to installation?",
      answer: "It depends on the size, the system, the glass and how quickly approvals come. No single duration fits every project. The stages run in a fixed order, and the longest waits are usually approvals and special glass, so the programme should be built from the stages, not a rule of thumb.",
    },
    {
      question: "When should a facade consultant be appointed?",
      answer: "Early, ideally at concept or schematic design. Decisions on grid, glass, system type and movement are hard to change later. A facade consultant helps set performance requirements, check design intent and review the contractor's submissions, which saves rework at the later, more expensive stages.",
    },
    {
      question: "What are shop drawings and why do they take time?",
      answer: "Shop drawings are the manufacturer's detailed drawings of what will be made and installed, with every section, anchor and joint shown. They take time because they must be coordinated with the structure, checked, commented on and approved before fabrication can safely start.",
    },
    {
      question: "Why does a facade mock-up come before full production?",
      answer: "A mock-up shows the real assembly, finish and workmanship at full size before the whole building is made. Problems found on one bay are cheap to fix. The same problems found after fabrication or installation can mean remaking many units and moving the handover date.",
    },
  ],
  body: [
    { t: "p", x: "A facade is not bought off a shelf. It is designed for one building, tested against that building's loads, drawn in detail, made in a factory and installed on a structure that is still being finished. Each of those steps depends on the one before it. When a project runs late, the cause is usually that an early stage was rushed or skipped, and the delay was paid for later. This article walks through the sequence in order, so you can see where decisions are needed and who owes what to whom." },
    { t: "h2", x: "Concept and early design" },
    { t: "p", x: "At concept stage the architect sets the look of the building: the grid, the proportion of glass to solid wall, the materials, the depth of the elevation. Questions that seem purely visual have large consequences. A tall floor-to-floor height, a deeply modelled facade or a very large glass size all affect weight, structure, cost and how the pieces can be lifted into place." },
    { t: "p", x: "This is the best time to appoint a {{facade-consultant|facade consultant}}, because the cheapest changes are made here. They can advise on which system suits the design, such as {{/journal/stick-vs-unitised-curtain-wall|stick or unitised curtain wall}}, and flag early where the idea will be difficult to build, test or maintain. Keep an open mind about the details that are not yet fixed." },
    { t: "p", x: "Early design is also when the structure and the facade must agree on their interface. The slab edge, the position of columns and the way loads travel to the frame all need to be settled before detailed design. If the structural engineer later moves an edge or changes a beam depth, every anchor and bracket on the elevation may change with it. A short coordination meeting at this stage costs little and prevents a long list of revisions later." },
    { t: "p", x: "Think about maintenance and replacement now as well. Where will the cleaning cradle run? How will a broken pane be lifted out and replaced? A facade that looks wonderful but cannot be reached or repaired creates a permanent cost for the owner. These questions are easy to answer on a sketch and very hard to answer on a finished building." },
    { t: "h2", x: "Performance brief and specification" },
    { t: "p", x: "The concept becomes a document the contractor can price and build against. The specification sets what the facade must do: wind load, water and air performance, thermal and solar targets, acoustic needs, finish quality and the tests required. It names the materials and sets the tolerances." },
    { t: "p", x: "The more precise this document is, the fewer arguments occur later. A vague line such as 'high performance glass' invites substitution. A specification that states the required values and the test method leaves little room for dispute. The values come from the project, so they are confirmed with the facade consultant and not copied from another building." },
    { t: "img", id: "timeline-1", cap: "Each stage hands a more detailed version of the same facade to the next." },
    { t: "p", x: "Write the specification so that it can be checked. For each requirement, ask how it will be proved: by calculation, by a laboratory report, by a mock-up or by a site check. If no proof is named, the requirement is only a wish. Naming the proof at specification stage also tells bidders what they must price, which removes a common source of later disagreement about who pays for testing." },
    { t: "h2", x: "Tender, selection and award" },
    { t: "p", x: "Facade work is usually tendered to specialist contractors. Compare bids on more than price. Ask what system is proposed, what tests exist for it, how the work is split between design, supply and installation, and who is responsible for the interfaces with the structure and other trades. A low price that quietly excludes anchors, scaffolding, sealants or testing is not low." },
    { t: "p", x: "Before awarding, agree what the manufacturer needs from you and by when. Our note on {{/journal/what-to-send-a-facade-manufacturer|what to send a facade manufacturer}} lists the drawings, loads and finishes that save weeks of clarification later." },
    { t: "h2", x: "Engineering and shop drawings" },
    { t: "p", x: "After award, the manufacturer turns the design intent into buildable detail. Engineers size the frame, check the glass and design the anchors. Then {{shop-drawings|shop drawings}} are prepared, showing every section, joint, fixing and tolerance, and coordinated with the real structure. Slab edges, column positions and openings seldom match the earliest design exactly." },
    { t: "p", x: "This stage takes longer than most people expect, because it runs as a loop. The manufacturer submits, the consultant and architect comment, the manufacturer revises, and the cycle repeats until the drawings are approved. Slow, unclear comments cause the longest hold-ups. Our guide to {{/journal/reading-facade-shop-drawings|reading facade shop drawings}} helps reviewers respond quickly and usefully." },
    { t: "h2", x: "Testing and the mock-up" },
    { t: "p", x: "Before the full building is made, a representative assembly is tested and a {{mock-up|mock-up}} is built. Laboratory tests measure how the sample behaves under wind pressure, water and air, as described on our {{/testing|testing page}}. A site or factory mock-up shows the finish, joints, glass and workmanship at full size for the design team to inspect." },
    { t: "p", x: "Treat the mock-up as a decision point, not a ceremony. Inspect colour, flatness, sealant lines, alignments and how the facade meets the structure. Record every comment and agree what will change. Approval of the mock-up becomes the reference standard for production, so see {{/journal/facade-mock-up-review|how to review a facade mock-up}} before the visit." },
    { t: "p", x: "Keep a log of decisions during this phase. When a reviewer asks for a change, record who asked, what changed and whether the cost or programme moved. A log turns a long drawing review from a series of arguments into a short list of open items, and it gives the client a clear view of why a date shifted." },
    { t: "p", x: "Approvals also have to be given by the right people. A drawing marked approved by someone without authority is not approved. Agree at the start who signs off architecture, structure, fire and services interfaces, and how quickly each must respond. Slow or unclear sign-off is, more often than any factory delay, what pushes a facade programme out." },
    { t: "h2", x: "Fabrication and delivery" },
    { t: "p", x: "Once drawings and the mock-up are approved, the factory cuts, machines, finishes and assembles the components. Long-lead items, especially special glass and coatings, should have been ordered as early as the approvals allow. Delivery is planned against the installation sequence so that materials arrive in the order they are needed and are stored safely on site." },
    { t: "p", x: "Quality checks happen here, not only on site. Ask what inspections are done in the factory, how items are marked for traceability and how packing protects finishes in transit. Damage found at the factory costs little to correct. The same damage found after installation is a different matter." },
    { t: "p", x: "Delivery planning deserves its own short meeting. Site storage is usually tight, and a facade delivered too early may be damaged while one delivered too late stops the crews. Agree the unloading point, the lifting method and who is responsible for each pallet from the gate to the floor where it will be fitted." },
    { t: "h2", x: "Installation on site" },
    { t: "p", x: "Installation depends on the building being ready. Slab edges must be complete and survey-checked, access and hoisting arranged, and the site clear enough for the installers to work safely. The first completed bay is worth inspecting closely and comparing with the approved mock-up before the crews repeat it across the building." },
    { t: "ul", items: [
      "Survey the structure and agree any out-of-tolerance edges before installation.",
      "Confirm the sequence with the main contractor, including access and hoisting.",
      "Check anchors, sealant joints and interfaces at the first bay and again at intervals.",
      "Protect finished surfaces from plaster, paint, welding and cement.",
      "Record on-site testing as agreed, such as a water check on installed bays.",
    ] },
    { t: "p", x: "Site conditions change plans. Rain delays sealant work, a late slab pour blocks a hoist, and a neighbouring trade damages a finished panel. Hold short weekly coordination meetings with the main contractor and keep the facade sequence visible on the master programme. Early warning of a problem gives time to resequence rather than stop work." },
    { t: "h2", x: "Handover and what follows" },
    { t: "p", x: "Handover is not just a walk-through. The client should receive as-built drawings, finish and cleaning guidance, a maintenance plan, warranty terms and records of the tests carried out. A snagging list is agreed and closed out. Once the building is occupied, small defects tend to appear in the first monsoon or the first hot season, so decide who responds to them and how quickly." },
    { t: "p", x: "Ongoing care keeps the facade performing. Our {{/journal/facade-maintenance-checklist|facade maintenance checklist}} gives building teams a practical starting point. For the system most projects begin with, see {{/systems/curtain-wall|curtain wall}}." },
    { t: "note", x: "This outline is general. Stage durations, approval steps and required tests vary by project, and are confirmed with the facade consultant and the facade manufacturer." },
  ],
};

export default article;
