import type { Article } from "../journal";

const article: Article = {
  slug: "facade-installation-sequence-on-site",
  title: "Facade installation sequence on site: what happens in what order",
  seoTitle: "Facade Installation Sequence on Site",
  description: "How a curtain wall facade is installed on site, from survey and anchors to glazing, sealing and handover, and why the order of work matters.",
  excerpt: "A facade is installed in a set order, and each step depends on the one before. Knowing the sequence helps you plan access, spot delays early and ask better questions.",
  teaser: "Survey, anchors, frames, glass, sealing, checks. Why the order matters.",
  topic: "Enquiries",
  date: "2026-10-08",
  hero: "install-hero",
  card: "install-card",
  og: "/og/curtain-wall.jpg",
  terms: ["anchor", "mock-up", "unitised"],
  systems: ["curtain-wall"],
  faq: [
    {
      question: "What is the sequence of curtain wall installation on site?",
      answer: "The usual order is site survey, setting out, fixing anchors, installing frames or units, fitting glass or panels, sealing and drainage details, then cleaning, testing and handover. Unitised systems lift complete panels in place, while stick systems build the frame piece by piece on the building.",
    },
    {
      question: "How long does facade installation take?",
      answer: "There is no standard duration. It depends on the system, building height, access equipment, floor plate size, weather, supply of materials and how many trades share the elevation. A realistic programme comes from the installer after surveying the site and agreeing the delivery schedule.",
    },
    {
      question: "Why is a site survey needed before installation?",
      answer: "The structure as built is never exactly as drawn. A survey records slab edges, levels and openings so the facade can be set out and fabricated to fit. Without it, anchors may not line up and gaps may be too small or too large for the designed adjustment.",
    },
    {
      question: "What can delay a facade installation?",
      answer: "Common causes include late structure, unready slab edges, late approvals, delayed glass, poor access, bad weather, and clashes with other trades. Early coordination of the survey, drawings and delivery dates, along with clear hold points, reduces the chance that one late item stops the whole elevation.",
    },
  ],
  body: [
    { t: "p", x: "Facade work can look chaotic from the street: cradles, hoists, stacked frames and teams working at several levels. Underneath, it follows a firm order. Each step prepares the ground for the next, and a step done out of sequence usually has to be undone. For an owner, a developer or an architect, knowing this sequence makes it much easier to read a programme and to see where a delay on one task will spread." },
    { t: "h2", x: "Before anything reaches the building" },
    { t: "p", x: "Installation starts in the office. Approved drawings, material submittals and a delivery plan must be in place before the first frame is made. The facade contractor needs a clear picture of the structure, the available access, the hoisting method and the working areas for storage and assembly. Reading {{/journal/reading-facade-shop-drawings|facade shop drawings}} carefully at this stage prevents many of the problems that appear later." },
    { t: "p", x: "A {{mock-up|mock-up}} of a typical bay is often built and reviewed before production begins. It lets the architect, consultant and installer agree on appearance, fit, sealing details and the method of assembly while changes are still cheap. Our article on the {{/journal/facade-mock-up-review|facade mock-up review}} explains what to look at. Approving the mock-up in writing gives the site team a reference for the whole job." },
    { t: "p", x: "Logistics deserve the same attention as drawings. Decide where materials will be unloaded, where they will wait, and how they will travel to the right floor. Frames and glass delivered in the wrong order, or a day too early with nowhere to store them, create damage and lost time. A simple delivery schedule tied to the installation sequence, with clear labelling of every crate, keeps the site tidy and the crews working." },
    { t: "h2", x: "Site survey and setting out" },
    { t: "p", x: "The building as built never matches the drawing exactly. Slab edges can be a little out of line, levels may vary, and openings may be a different size. A survey records the real positions of the structure, and the results are compared with the design assumptions. If the deviation is more than the system is designed to absorb, a decision is needed before fabrication, not on the scaffold." },
    { t: "p", x: "Setting out then marks the grid lines, levels and anchor positions on the structure. Accuracy here is critical because every later part is located from these marks. A small error at the first floor is carried up the building. Good teams establish control lines and levels, check them regularly, and record the results so any dispute about the structure can be resolved with facts." },
    { t: "img", id: "install-1", cap: "Every part of the facade is positioned from setting-out marks, so an early error is carried up the building." },
    { t: "h2", x: "Fixing the anchors" },
    { t: "p", x: "An {{anchor|anchor}} connects the facade to the building structure and carries its loads. In a curtain wall, anchors are usually fixed to the slab edge or beam and are adjustable in several directions to absorb construction tolerances. They are installed before the frames and checked for position and alignment. Our article on {{/journal/curtain-wall-anchors-and-slab-edges|curtain wall anchors and slab edges}} covers this connection in more detail." },
    { t: "p", x: "Anchor installation is a hold point in a careful project. The method of fixing, such as cast-in channels or post-installed bolts, is chosen by the designer, and any change on site needs engineering approval. Checks usually include position, alignment, fixing details and the condition of the structure. Skipping this inspection to save time is one of the most expensive shortcuts on a facade job." },
    { t: "h2", x: "Installing frames or units" },
    { t: "p", x: "How the main elements go in depends on the system. In a {{stick-system|stick system}}, individual mullions and transoms are fixed to the anchors piece by piece and the frame is assembled on the building. In a {{unitised|unitised}} system, factory-built panels, often including glass, are lifted into place and linked to their neighbours. The trade-offs are explained in {{/journal/stick-vs-unitised-curtain-wall|stick versus unitised curtain wall}}." },
    { t: "p", x: "Stick installation needs more work at height and a longer period of exposure, but it is flexible and easy to transport. Unitised installation moves much of the work to the factory and speeds up the closing of the building, but it demands accurate setting out, careful logistics and hoisting capacity. Either way, frames are aligned, levelled and fixed with attention to expansion and movement allowances." },
    { t: "h2", x: "Glass, panels and the weather line" },
    { t: "p", x: "Once the frames are in position, glass or opaque panels are fitted. In a stick system this is done opening by opening. Large panes need suction lifting equipment and a clear process for handling, because dropped or chipped glass is an expensive error. Gaskets, pressure plates and caps are fitted according to the approved detail, and fixings are tightened to the specified method." },
    { t: "p", x: "The weather line is formed as the work proceeds. Perimeter seals, flashings, firestops and the drainage path behind the glazing all need to be completed in the right order and inspected before they are covered. A seal hidden behind a finished panel cannot be seen again. For that reason, hold points often require an inspection photograph or a signed check before the next element is closed over." },
    { t: "h2", x: "Sealing, cleaning and protection" },
    { t: "p", x: "External sealing is done once the framework is stable, and the surfaces are clean and dry. The work is covered in more detail in {{/journal/sealants-and-gaskets-in-facades|sealants and gaskets in facades}}. After sealing, the facade is protected from other trades, since plaster, paint, welding and grinding can all damage glass and finishes. Protective films should be kept in place until the last practical moment." },
    { t: "p", x: "Cleaning is planned near the end, since early cleaning is wasted if other trades are still working above. Care is needed to avoid scratching coated glass or damaging finishes with abrasive tools. The cleaning method, the products allowed and the access equipment should be agreed beforehand, and the area should be checked in good light before the final handover." },
    { t: "h2", x: "Inspection, testing and handover" },
    { t: "p", x: "Quality checks run throughout, but several come at the end. Typical checks include alignment and appearance, sealing and drainage, hardware operation and the completeness of records. Where the contract calls for field testing, such as a water test on selected areas, it is carried out by an agreed method, and the results are recorded. Our guide to {{/journal/what-astm-e331-tests|what ASTM E331 tests}} explains what one such laboratory test measures." },
    { t: "ul", items: [
      "As-built records of the installed facade, including any approved changes.",
      "Inspection and test records for anchors, seals and drainage.",
      "Cleaning, maintenance and replacement instructions for the owner.",
      "A list of outstanding items, and an agreed plan to close them.",
      "Warranty documents that state what is covered and for how long.",
    ] },
    { t: "p", x: "A clear handover pack helps the owner maintain the facade over its life. It also protects the installer, because it shows the work was inspected and recorded as agreed." },
    { t: "h2", x: "Access, hoisting and safety" },
    { t: "p", x: "Installation depends on how people and materials reach the facade. Options include hanging platforms, mast climbers, scaffolds, tower cranes and building maintenance units, and each has limits on reach, load and the speed of work. The choice affects the programme and the sequence, because some equipment can serve only certain elevations at a time. Agree access early, with the structure team, so slab edges and temporary works are ready when needed." },
    { t: "p", x: "Safety planning is part of the sequence, not an add-on. Edge protection, exclusion zones below the work, lifting plans for heavy panels and rules for working in wind all affect when and how work can proceed. A method statement should explain these points in plain language, and the site team should brief every crew on them. Work stops when conditions are unsafe, and the programme should allow for that." },
    { t: "h2", x: "Where programmes slip" },
    { t: "p", x: "Delays often start before the installer arrives: a late structure, an unfinished slab edge, or an approval that has not been issued. Others come from material, such as glass or finishes that take longer than expected. On site, weather, poor access and clashes with other trades are frequent causes. Because each step depends on the last, one late item can hold up a whole elevation." },
    { t: "p", x: "The best protection is early coordination. Agree the survey date, the drawings approval route and the delivery windows at the start, name the hold points, and review progress by elevation. Ask the installer for a method statement that explains the sequence, access and safety plan. It is much easier to fix a sequence on paper than on a hanging platform." },
    { t: "note", x: "This guidance is general. The sequence, access methods, hold points and testing are confirmed for each project with the facade consultant and the installer." },
  ],
};

export default article;
