import type { Article } from "../journal";

const article: Article = {
  slug: "facade-mock-up-review",
  title: "Facade mock-ups: what to build, test and record",
  seoTitle: "Facade Mock-Ups: Review and Testing",
  description: "A guide to facade mock-ups: choose representative interfaces, agree criteria, inspect workmanship, test performance and carry lessons into production.",
  excerpt: "A mock-up is a chance to find a difficult detail while there is still time to change it. Make it representative, document it, and carry the result into production.",
  teaser: "Turn one trial bay into a useful project decision.",
  topic: "Testing",
  date: "2026-10-07",
  hero: "e331-hero",
  card: "e331-card",
  og: "/og/quality-safety.jpg",
  terms: ["mock-up", "astm-e331", "shop-drawings", "gasket"],
  systems: ["curtain-wall", "structural-glazing", "casement-windows"],
  faq: [
    { question: "What is the purpose of a facade mock-up?", answer: "It lets the project team review appearance, constructability and, when specified, measured performance on a representative assembly before repeating the detail across the building." },
    { question: "Should the mock-up include a corner or opening window?", answer: "Include the interfaces that pose real project risks, such as a corner, opening, floor line or system change. A flat bay cannot demonstrate every junction; the consultant should define the specimen from the actual design." },
    { question: "Does a passed mock-up mean the whole building passes?", answer: "No. It shows the performance of the specimen under the agreed test conditions. Production materials, workmanship, site interfaces and later changes still need quality checks and any specified field tests." },
  ],
  body: [
    { t: "p", x: "A facade {{mock-up|mock-up}} is most valuable before the building has hundreds of identical bays. It makes the design physical: frames can be assembled, glass can be installed, corners can be viewed and water routes can be observed. Some projects also put the specimen through laboratory tests for air, water and structural response. The point is to answer specific questions early and record what changes. A beautiful sample that omits the difficult interfaces, or a test result that cannot be tied to the production design, offers much less protection." },
    { t: "h2", x: "Decide what question the sample must answer" },
    { t: "p", x: "The architect may need to approve colour, sightlines and reflections. The facade consultant may need to assess a stack joint, water barrier and movement detail. The contractor may need to prove an installation sequence. Write those goals down before choosing the specimen. A visual sample and a performance mock-up have related but different roles; one might be a room-size corner viewed in natural light, while another must fit a test rig and include the worst representative details." },
    { t: "p", x: "Select a bay from the actual project, not an easy generic rectangle. Consider a floor line, an opening sash, a corner, a cladding interface, a door threshold or a roof junction if that is where the uncertainty lies. Review how the sample will be anchored and whether the test support represents the building's movement and stiffness. The approved specimen drawings should identify every glass type, profile, gasket, sealant and fixing. A later substitution can make the original result less relevant." },
    { t: "h2", x: "Agree the test plan before assembly" },
    { t: "p", x: "The project specification should state which properties are measured, the relevant procedures, pressures or loads, acceptance criteria and test sequence. Air leakage, water penetration and structural response measure different things. A water check that finds a local defect should lead to a documented diagnosis and repair, then a retest as the agreed plan requires. Avoid describing any one spray or hose check as proof of all wind-driven rain performance; the test method and conditions must match the claim." },
    { t: "p", x: "Write down who witnesses each stage and how deviations are handled. The consultant, architect, contractor and laboratory may have different approval roles. Record instrument calibration, environmental conditions where relevant, specimen changes and photographs of concealed details. If a test fails, preserve the first observation before sealing over it. The failure may reveal a missing baffle, an incorrect gasket, a poor corner joint or a drawing that cannot be built consistently." },
    { t: "img", id: "e331-1", cap: "Water testing is useful when its method, pressure and acceptance criteria are defined in advance." },
    { t: "h2", x: "Use construction as an inspection" },
    { t: "p", x: "Watch how components arrive and fit. Are cut ends protected where required? Can installers reach the fasteners and make a continuous seal? Does the glass sit on its supports as drawn? Can a sash be adjusted without removing adjacent panels? Note every workaround. A detail that passes once only because a specialist spends hours repairing it may be hard to repeat on site. Production-friendly details should be part of the outcome, not an afterthought to the test report." },
    { t: "p", x: "Check appearance at a realistic viewing distance and in more than one light condition. Glass colour and reflectance can change with angle and surrounding light; coatings and cladding finishes may read differently beside each other. Compare to the approved sample and schedule, then record the chosen appearance limits. If a visual decision changes the glass or frame make-up, assess whether the performance mock-up still represents the selected design." },
    { t: "h2", x: "Carry lessons into fabrication" },
    { t: "p", x: "Close the loop with a revised drawing set, component list and method statement. Tag each mock-up finding with its design response and responsible party. If an outlet moved or a gasket changed, update every affected detail and purchasing schedule. Retain a controlled sample or clear photographic record for future comparison. Train production and installation teams on the approved method; a successful test of one specimen cannot compensate for inconsistent work in hundreds of bays." },
    { t: "p", x: "Site inspections and any specified field tests still matter. The laboratory specimen may use carefully controlled dimensions, while the real building includes varying slabs, interfaces with other trades and weather exposure. Sample early installed bays, particularly those that contain the same difficult junctions. Compare the actual materials and process with the approved mock-up record. If the site solution changes, obtain review before calling it equivalent." },
    { t: "h2", x: "Keep the evidence usable" },
    { t: "p", x: "The final pack should contain specimen drawings, materials, photographs, test plan, raw observations, formal report, repair and retest history, approval comments and the final production revisions. A short decision log is often more useful than a large report with no link to the current shop drawings. It tells the next team why a detail looks unusual and what must not be changed. Used this way, a mock-up is a design tool and a quality reference, not a ceremonial box to tick." },
    { t: "h2", x: "Choose a representative test specimen" },
    { t: "p", x: "A useful specimen includes the component most likely to challenge the design, not just the most common flat bay. An opening window introduces moving seals; a floor line introduces a stack joint; a corner introduces geometry and movement in two directions. If the full project has several distinct systems, one specimen may not represent all of them. Agree with the facade consultant which risk each sample covers and which conditions remain to be checked by calculation, visual review or site testing." },
    { t: "p", x: "Keep a record of the exact build. List glass make-up, profile series, gaskets, setting blocks, sealants, fasteners, bracket positions and installation sequence. Photograph concealed joints before glazing. Mark any repair or adjustment on the drawing as it happens. A passing report without this build record may be hard to use when production starts: the team may not know whether the tested corner used the original detail or a last-minute change made at the laboratory." },
    { t: "h2", x: "Respond properly to a failed observation" },
    { t: "p", x: "Failure can be valuable if it is investigated. Record where water first appeared, the stage and conditions of the test, and whether it followed a profile chamber, gasket corner or perimeter joint. Do not immediately coat the outside with sealant and call the problem solved. A repair should have a clear cause, a revised detail and an installation method that can be repeated on the building. Retest in the agreed sequence and keep both the original and final results in the project record." },
    { t: "p", x: "Visual comments also need closure. If the architect asks for a slimmer cap, a different glass colour or a smaller joint, record the resulting design change and check its effect on drainage, movement and procurement. A mock-up review works best when each discipline sees the same current specimen. The approved appearance sample, test specimen and production drawings should tell one coherent story. Otherwise a project can approve one appearance, test another assembly and build a third." },
    { t: "note", x: "Testing demonstrates the performance of the specimen under specified conditions. It is not a claim that Fenza has passed a test or that every installed facade bay has the same performance." },
  ],
};

export default article;
