import type { Article } from "../journal";

const article: Article = {
  slug: "facade-warranty-and-defect-liability",
  title: "Facade warranty and defect liability: what to ask for",
  seoTitle: "Facade Warranty and Defect Liability",
  description: "A facade warranty is only as useful as its wording. What it should cover, what it usually excludes, and the questions to ask before you sign a contract.",
  excerpt: "A warranty is a promise written on paper, and its value sits in the details. Scope, exclusions, who responds and how a claim is made matter more than the headline period.",
  teaser: "A warranty is only as good as its wording. What to read before you sign.",
  topic: "Enquiries",
  date: "2026-10-08",
  hero: "warranty-hero",
  card: "warranty-card",
  og: "/og/cladding.jpg",
  terms: ["sealant-joint", "facade-consultant", "shop-drawings"],
  systems: ["curtain-wall", "cladding"],
  faq: [
    {
      question: "What does a facade warranty usually cover?",
      answer: "Typically it covers defects in materials and workmanship that appear within a stated period, such as water leakage through a faulty joint, failure of a finish, or glass seal failure. The scope, period, exclusions and claim process vary, so read the written wording and ask what is separate from manufacturer warranties.",
    },
    {
      question: "What is the difference between a warranty and defect liability?",
      answer: "Defect liability is a contractual period during which the contractor must repair defects in the work. A warranty is a separate written promise, often from a manufacturer or the installer, about specific materials or performance. They may overlap, so check how each applies and how they are claimed.",
    },
    {
      question: "What is usually excluded from a facade warranty?",
      answer: "Exclusions often include damage from impact, misuse, lack of maintenance, alterations by others, structural movement outside design limits and normal wear of soft parts. Cleaning with unapproved products can also void cover. Read the exclusions closely and ask for examples that apply to your building.",
    },
    {
      question: "How do I make a facade warranty claim?",
      answer: "Follow the process in the warranty document: report the defect in writing within the notice period, give the location and photographs, allow access for inspection, and keep maintenance records. Delays or missing records can weaken a claim, so keep the handover pack and inspection logs organised.",
    },
  ],
  body: [
    { t: "p", x: "When a facade contract is signed, the warranty is often treated as a formality in the closing pages. Years later, when a leak appears in a bedroom or a coating fades on one elevation, it becomes the most important document in the file. The words decide who responds, what they must fix and at whose cost. Reading it carefully before signing is much cheaper than interpreting it during a dispute." },
    { t: "h2", x: "Warranty and defect liability are not the same" },
    { t: "p", x: "Two terms are often mixed up. A defect liability period is set by the main contract. During it, the contractor must come back and repair defects in the work, usually at their own cost. A warranty is a separate written promise, often from the installer or the manufacturer of a product, about specific materials, finishes or performance. A single facade can carry several of each, with different start dates and different people responsible." },
    { t: "p", x: "This matters because gaps can appear between them. A finish may carry a manufacturer's warranty that only applies if specific cleaning and installation rules were followed. A glass unit may carry its own seal warranty. The installer may offer a workmanship warranty. Ask for a simple schedule that lists every warranty on the facade, who gives it, what it covers, when it starts and how long it runs." },
    { t: "h2", x: "What a good warranty should state" },
    { t: "p", x: "A useful warranty is specific. It names the parts of the facade it covers, such as the framing system, the glass units, the finishes and the weather seals. It states what counts as a defect and what the responsible party will do about it, whether that is repair, replacement or a payment. It also gives the start date, which is usually completion or handover, and not the delivery date of the first material." },
    { t: "ul", items: [
      "The parties: who gives the warranty and who can claim under it.",
      "The scope: which components, finishes and performance items are covered.",
      "The period: the start date and length for each item.",
      "The remedy: repair, replacement, labour, access equipment and removal costs.",
      "The claim process: whom to notify, how, and within what time.",
      "The conditions: maintenance, cleaning and inspection duties on the owner.",
    ] },
    { t: "img", id: "warranty-1", cap: "A warranty is a bundle of separate promises, each with its own scope, period and conditions." },
    { t: "h2", x: "Who pays for access and removal" },
    { t: "p", x: "On a tall building, the repair itself may be a small part of the cost. Reaching the defect needs a cradle or platform, and removing and refitting adjacent parts can be time-consuming. If the warranty says the manufacturer will supply a replacement panel but not fit it, the owner may carry most of the cost. Ask directly whether the warranty includes access, labour, removal of the failed item and refinishing, or only the replacement material." },
    { t: "p", x: "Also ask about the response time. A leak during the monsoon needs a quick visit and a temporary fix, even if a final repair takes longer. The document should say who to call, what response is expected and whether emergency measures are covered. A clear contact route is more useful than an impressive-sounding period." },
    { t: "h2", x: "Common exclusions to read carefully" },
    { t: "p", x: "Every warranty has exclusions, and they are not a sign of bad faith. A responsible supplier cannot cover impact damage, vandalism or unforeseeable events. Yet some exclusions are broad enough to remove most of the practical value. Read them against a realistic list of problems on your building and ask for examples of what would and would not be accepted." },
    { t: "ul", items: [
      "Damage from impact, misuse, accident or extreme events.",
      "Normal wear and ageing of soft parts such as gaskets and sealant.",
      "Defects caused by alterations or repairs by others.",
      "Failure to follow cleaning and maintenance instructions.",
      "Movement of the building structure beyond the limits in the design brief.",
      "Cosmetic variation within the agreed acceptance standard.",
    ] },
    { t: "p", x: "Pay special attention to the treatment of the {{sealant-joint|sealant joints}}, since they are among the most likely places for a defect to appear. Some warranties limit cover for sealants to a shorter period than the framing, or exclude them unless inspected regularly. The background is in our article on {{/journal/sealants-and-gaskets-in-facades|sealants and gaskets in facades}}." },
    { t: "h2", x: "Maintenance duties belong to the owner" },
    { t: "p", x: "A warranty often depends on the owner maintaining the facade as instructed. That can include regular cleaning with approved products, periodic inspection of seals and drainage, and keeping records. If those duties are not met, a claim can be rejected even for a genuine defect. Ask for the maintenance instructions in plain language, before handover, and check they are realistic for the building and the budget." },
    { t: "p", x: "Our {{/journal/facade-maintenance-checklist|facade maintenance checklist}} gives a starting point for routine checks. Keep dated records and photographs of inspections, cleaning and any repairs. If a claim arises, those records show that the facade was cared for, and they help the installer identify the cause of the problem more quickly." },
    { t: "h2", x: "Link the warranty to the approved documents" },
    { t: "p", x: "A warranty promises that the facade matches what was approved. That is why the approved {{shop-drawings|shop drawings}}, material submittals, test records and mock-up approval should be part of the handover. If a defect appears, the first question is whether the installed work matches those documents. Without them, it is hard to show whether the fault lies in the design, the materials or the installation." },
    { t: "p", x: "Where performance claims matter, ask what evidence supports them. A product might have a laboratory test on a sample, and that tells you something about the design, though not about every installed unit. Our guide to {{/journal/reading-facade-shop-drawings|reading facade shop drawings}} helps you check that the drawings describe what you expect to be built, before the warranty begins." },
    { t: "p", x: "Coatings and glass units are often covered by separate manufacturer terms. For finishes, the typical conditions concern installation, cleaning and exposure, and a claim may require proof that the surface was treated as instructed. For glass, a sealed-unit warranty usually concerns failure of the edge seal, shown by moisture between the panes. Ask what evidence is needed, how a failed unit is replaced and whether the cost of access is included." },
    { t: "p", x: "Colour change is another item to settle early. Every finish ages in sunlight, so the warranty should define what amount of change counts as a defect and how it is measured. Without that definition, a complaint about fading becomes a matter of opinion. Agreeing a reference sample and a method of comparison at the start gives both sides something objective to check against." },
    { t: "h2", x: "What to do when a defect appears" },
    { t: "p", x: "Act promptly and in writing. Record the date, the location and the conditions, such as heavy rain or wind, and take clear photographs. Notify the party named in the warranty within the time allowed, and keep a copy of the message. Give access for inspection and avoid repairs by others before the responsible party has seen the problem, since that can affect the claim." },
    { t: "p", x: "If the cause is unclear, ask for a joint inspection that includes the installer, the facade consultant and, where relevant, the product manufacturer. A controlled test of the affected area can help to identify the entry point. Record the findings and the agreed repair method, then check the same area after the next heavy rain to confirm that the repair has worked." },
    { t: "h2", x: "Involve the right people early" },
    { t: "p", x: "A {{facade-consultant|facade consultant}} can review the draft warranty alongside the specification and the contract, and point out gaps. A lawyer can check that the wording is enforceable and that the parties are named correctly. These checks cost little compared with a dispute. It is much easier to ask for a clearer clause before signing than to argue its meaning after a leak has damaged a finished interior." },
    { t: "p", x: "Also check who stands behind the promise. A warranty from a company that no longer trades is of little use. Ask whether it is backed by the manufacturer, by an insurer or by a bond, and what happens if the installer is sold or closed. Where several parties are involved, a single point of contact for claims saves valuable time when a problem appears." },
    { t: "h2", x: "A short checklist before you sign" },
    { t: "ol", items: [
      "List every warranty and defect liability period, with start dates and parties.",
      "Read the scope, the exclusions and the conditions for each one.",
      "Confirm who pays for access, removal, refitting and refinishing.",
      "Agree a clear claim process and a named contact.",
      "Keep the approved drawings, test records and maintenance instructions in the handover pack.",
      "Ask the facade consultant to review the wording against the specification.",
    ] },
    { t: "p", x: "The goal is not to find a perfect warranty, because none exists. It is to understand what protection you have, what you must do to keep it, and how to use it when needed." },
    { t: "note", x: "This guidance is general and not legal advice. Warranty terms, periods and responsibilities are confirmed for each project with the facade consultant and a legal adviser." },
  ],
};

export default article;
