import type { Article } from "../journal";

const article: Article = {
  slug: "frameless-glass-doors-hardware-floor-and-header",
  title: "Frameless glass doors: hardware, floor and header",
  seoTitle: "Frameless Glass Doors Guide",
  description: "A frameless glass door depends on hardware, floor and header more than the glass. What each does, what to check, and how to avoid common faults.",
  excerpt: "A frameless glass door looks simple, but the glass is carried by fittings, a floor pivot and a header. Getting those three right decides how it works for years.",
  teaser: "The glass is the easy part: check the fittings, floor and header.",
  topic: "Windows & doors",
  date: "2026-10-08",
  hero: "fgdoor-hero",
  card: "fgdoor-card",
  og: "/og/frameless-glass-doors.jpg",
  terms: ["patch-fitting", "toughened-glass", "glazing"],
  systems: ["frameless-glass-doors"],
  faq: [
    {
      question: "What are the parts of a frameless glass door?",
      answer: "The glass leaf, the fittings fixed to it (patch fittings or rails), the pivot or hinge hardware at the top and bottom, a floor spring or closer, the lock and handle, and the structure above and below that carries the load. The glass is only one component.",
    },
    {
      question: "Why must frameless glass doors use toughened glass?",
      answer: "The door is exposed to impact, and the fittings put local stress on the glass at holes and clamps. Toughened glass is much stronger than ordinary glass and breaks into small blunt pieces. Safety glazing requirements in the applicable code also usually call for it.",
    },
    {
      question: "Why does my glass door drop or drag on the floor?",
      answer: "Common causes are a worn or loose pivot, a floor that has settled or is not level, a header that has moved, or loose fittings on the glass. Check the hardware and the supporting structure before adjusting. Repeated dragging can chip the glass edge.",
    },
    {
      question: "Can a frameless glass door be used outdoors?",
      answer: "It can, but weather changes the design. Rain, wind, dust and temperature movement affect seals, hardware and drainage at the threshold. The hardware must be suited to outdoor use and the details must keep water out. This should be specified and confirmed per project.",
    },
  ],
  body: [
    { t: "p", x: "A frameless glass door seems to be the simplest door there is: a single sheet of glass, a handle and little else. In practice it is one of the more demanding to specify. With no frame to share the load, the weight and every opening movement pass through a few small metal parts. If they are well chosen and well fixed, the door works smoothly for years. If not, it drops, drags, rattles or, in the worst case, damages the glass. This article looks at the three things that matter most: the hardware, the floor and the header." },
    { t: "h2", x: "How the door is actually held" },
    { t: "p", x: "A frameless leaf is carried at the top and the bottom. At the top it usually pivots in a fitting fixed to the header or the glass above. At the bottom it turns on a pivot set into the floor, often connected to a floor spring or closer that returns the door to a closed position. In between there is nothing to support the weight except the glass itself." },
    { t: "p", x: "The loads are therefore concentrated. The weight of the leaf sits on the bottom pivot, and the top fitting holds the leaf upright and resists sideways forces. People pushing and pulling on the handle apply further loads at every use. Each connection must be sized for the leaf weight and the traffic it will face." },
    { t: "p", x: "Because so few parts carry so much, tolerance matters. The top and bottom pivots must sit on the same vertical line, or the door will bind as it swings. The gap between the leaf and the floor, the wall and the neighbouring glass must be consistent and wide enough to allow movement. When the gaps are uneven, the eye picks it up immediately, and the door starts to rub." },
    { t: "h2", x: "The glass and why it is toughened" },
    { t: "p", x: "Frameless doors use {{toughened-glass|toughened glass}}, which is heat-treated to be much stronger than ordinary glass and breaks into small, blunt pieces. Toughening also matters for a practical reason: all holes, notches and cut-outs must be made before the treatment. Glass cannot be drilled or altered afterwards, so the hardware layout must be fixed before the glass is ordered." },
    { t: "p", x: "Thickness depends on the leaf size, the use and the hardware, and is set by the supplier and the specification. For the background on glass types, see {{/journal/choosing-facade-glass|choosing facade glass}}. Pay attention to edge finish too. A polished edge is safer to handle and less prone to chips than a rough one." },
    { t: "img", id: "fgdoor-1", cap: "The glass leaf is carried by a few small fittings, so the loads concentrate at those points." },
    { t: "h2", x: "Patch fittings and how they grip" },
    { t: "p", x: "A {{patch-fitting|patch fitting}} is a metal clamp fixed to a corner or edge of the glass. It holds the top and bottom pivots, or a lock, and transfers the loads into the hardware. Fittings may clamp the glass between plates or pass bolts through drilled holes. Either way, the glass must be protected from direct contact with the metal by a soft liner or gasket." },
    { t: "p", x: "Ask how the fitting grips and what happens over time. Do the fixings loosen with repeated use? Can they be tightened without removing the door? Are replacement parts available from the same manufacturer? A fitting that cannot be serviced becomes a maintenance problem in a busy entrance." },
    { t: "p", x: "Edges deserve care as well. The glass edge sits close to metal, stone or another leaf, so a small impact can chip it. Specify finished edges, keep the clearance consistent and fit protective stops where the door could swing into a wall. A chip at the edge of toughened glass can become the starting point of a larger failure, so a damaged leaf should be assessed promptly and not left in service." },
    { t: "h2", x: "The floor: pivot, spring and threshold" },
    { t: "p", x: "The floor carries the weight and sets the line of the door. The pivot or floor spring sits in a box cast into or set below the finished floor, so it has to be located accurately before finishes are laid. A box that is a few millimetres off line is a door that drags forever." },
    { t: "ul", items: [
      "Fix the floor box position from the approved drawing, not by eye.",
      "Check that the floor is level and stable under the pivot.",
      "Keep the box accessible for adjustment and servicing.",
      "Allow for the finished floor thickness when setting the box.",
      "Provide drainage if the door is outdoors or in a wet area.",
      "Check the gap at the threshold so that the door clears with room to spare.",
    ] },
    { t: "p", x: "Floor finishes are laid by another trade, so coordinate early. A tile level that changes after the box is installed is a common cause of dragging and uneven gaps." },
    { t: "h2", x: "The header and what carries it" },
    { t: "p", x: "The top pivot needs a solid, straight, correctly aligned support. This may be a metal header, a fixed glass panel above or a fitting fixed into the structure. Whatever it is, it must not deflect under the door's movement or the building's own settlement. If the header moves, the top pivot moves, and the door goes out of line." },
    { t: "p", x: "Check the load path. The header must be fixed to something that can carry the loads reliably. Plasterboard or thin cladding cannot. The facade consultant and the structural engineer should confirm the fixing, because the facade manufacturer can only fix to what the building provides. Compare with the system details on our {{/systems/frameless-glass-doors|frameless glass doors}} page." },
    { t: "p", x: "Think about how the header is finished. A top pivot hidden behind a trim must still be reachable, because it will need adjusting after the first months of use. Fixed ceilings or boxed headers that cannot be opened turn a five-minute adjustment into a repair job. Ask for an access panel or a removable cover in the drawings." },
    { t: "p", x: "Where two leaves meet, or a leaf meets a fixed glass panel, the joint needs attention. Gaps should be even and the edges protected. Some designs use a clamp or rail at the meeting line to carry a lock. Whatever is chosen, make sure the glass edges are not forced against one another as the building moves." },
    { t: "h2", x: "Locks, handles and seals" },
    { t: "p", x: "Locks and handles are fixed to the glass through further cut-outs or clamps. Choose hardware designed for the thickness of the glass and the door's use. A door that is used all day in a shopfront needs more robust hardware than one used occasionally in a private entrance." },
    { t: "p", x: "Sealing is a trade-off. A frameless door normally relies on brushes or small gaskets at the edges, so it will not seal as tightly as a framed door. For outdoor or air-conditioned locations, discuss with the manufacturer how air leakage, dust and water will be managed. Our article on {{/journal/slide-and-fold-doors-what-to-check|slide-and-fold doors}} covers similar questions for another door type, and our {{/testing|testing page}} explains what air and water tests measure." },
    { t: "p", x: "Think about use. A door in a quiet office lobby and a door at a busy shop entrance face very different duty. Heavy traffic, slamming and children hanging on handles all stress the hardware. Tell the supplier how the door will really be used, and ask for hardware chosen for that duty rather than for the lowest price." },
    { t: "p", x: "Installation order matters as well. Fit the glass last, after floors, ceilings and wall finishes are complete, so that it is not scratched or chipped by other trades. Protect the leaf with film or boards until handover, and check the alignment again once the building has settled." },
    { t: "h2", x: "Common faults and how to avoid them" },
    { t: "ol", items: [
      "Door drags or drops: check the floor pivot, the level of the floor and the header.",
      "Door will not stay closed: check the closer setting and the alignment.",
      "Rattling or looseness: check the fixings in the patch fittings.",
      "Chipped edges: check clearances and look for contact with the floor or frame.",
      "Cracked glass at a fitting: check for metal-to-glass contact and over-tightening.",
      "Water at the threshold: check drainage and the seal design for outdoor doors.",
    ] },
    { t: "p", x: "Most of these come from decisions made before installation: unclear drawings, late floor finishes or fixings to an unsuitable header. A good first step is to review the {{/journal/reading-facade-shop-drawings|shop drawings}} for all three load points." },
    { t: "h2", x: "Questions to ask the supplier" },
    { t: "ul", items: [
      "What glass thickness and treatment are proposed, and for what leaf size?",
      "How are the fittings fixed, and how are they adjusted or replaced?",
      "Where does the floor box sit, and who is responsible for setting it?",
      "What carries the header, and what loads does it assume?",
      "How is the door sealed, and what is its intended location?",
      "What maintenance does the hardware need, and who provides spare parts?",
    ] },
    { t: "note", x: "This guidance is general. Glass thickness, hardware ratings, fixings and details are confirmed per project with the facade consultant and the hardware manufacturer." },
  ],
};

export default article;
