import type { Article } from "../journal";

const article: Article = {
  slug: "glass-reflectivity-and-glare-for-neighbours",
  title: "Glass reflectivity and glare: choosing for the neighbours too",
  seoTitle: "Glass Reflectivity and Glare",
  description: "Highly reflective facade glass can dazzle neighbours and drivers. Learn what reflectance means, how coatings and angle change it, and what to check.",
  excerpt: "A facade is seen from outside as well as inside. The glass you choose for solar control can also reflect sun onto streets and neighbouring buildings.",
  teaser: "Solar control glass also reflects. Check what it does outside.",
  topic: "Performance",
  date: "2026-10-08",
  hero: "glare-hero",
  card: "glare-card",
  og: "/og/curtain-wall.jpg",
  terms: ["low-e-coating", "solar-heat-gain", "glazing"],
  systems: ["curtain-wall", "structural-glazing"],
  faq: [
    { question: "What is glass reflectivity?", answer: "Reflectivity, or reflectance, is the share of light that bounces off the glass surface instead of passing through. It is reported for the outside face and sometimes the inside face. A higher figure makes the glass look more mirror-like and can send more sunlight toward neighbours." },
    { question: "Can a glass facade cause glare for neighbours?", answer: "Yes. Sun striking a smooth, reflective surface can be redirected to roads, windows and outdoor spaces, depending on the sun angle, building shape and glass. Curved or tilted surfaces can concentrate the effect, so a reflection check is wise for large or prominent facades." },
    { question: "Does solar control glass always look reflective?", answer: "No. Some coatings reduce heat while staying fairly neutral and low in reflection, while others look distinctly mirror-like. Two units with similar heat performance can look very different outside, so compare reflectance figures and view a large sample in daylight." },
    { question: "How can I check glare before building?", answer: "Ask the facade consultant for a reflectance figure and a large sample viewed outdoors at different times of day. For prominent or curved facades, a specialist reflection study can model sun paths and show where light could land on neighbours and traffic." },
  ],
  body: [
    { t: "p", x: "Most glass decisions are made from the inside out. We ask how much heat and light the building takes in, and how its occupants feel. But a facade also faces the street, the road and the building next door. Glass that reduces heat inside by reflecting more of the sun can reflect that sun somewhere else. This article looks at the outside face of glass and how to choose without surprising the neighbours." },
    { t: "h2", x: "What reflectivity means" },
    { t: "p", x: "Reflectance is the proportion of light that bounces back from a surface. For glass it is given as a figure for the outside face and often the inside face. A clear single pane reflects little, so you see through it. A coated or tinted unit reflects more, and a strongly coated one can look like a mirror in bright light." },
    { t: "p", x: "Reflectivity is not the same as heat performance, though they are linked. A coating that rejects heat often does so partly by reflecting. Others absorb heat in the glass. Read the full specification, including visible light transmittance, solar factor and reflectance, rather than looking at one number. The basics of those figures are in {{/journal/choosing-facade-glass|choosing facade glass}}." },
    { t: "h2", x: "Where the glare goes" },
    { t: "p", x: "Reflected sunlight follows simple geometry. Light hits the glass at one angle and leaves at the same angle on the other side of the surface. A flat wall sends a reflection in one direction, so it can fall on a road or a facing window at certain hours and seasons. A curved or faceted facade can spread the light or gather it into a bright patch." },
    { t: "p", x: "The effect changes with the sun's path. Early and late in the day the sun is low, so reflections run along streets and into eye level. Higher sun sends light further away or up. A tilted surface angled toward the ground can send light downward onto pavements and vehicles. Orientation, building shape and surroundings all matter, and none can be judged from a drawing alone." },
    { t: "img", id: "glare-1", cap: "A reflection follows the sun's path, so its effect on a neighbour changes through the day and through the year." },
    { t: "h2", x: "How coatings change the outside view" },
    { t: "p", x: "A {{low-e-coating|low-E coating}} is a thin metallic layer that reflects heat radiation. Some versions are almost invisible and keep reflectance low, while stronger solar control versions look more reflective. The coating also sits on a specific surface of the {{double-glazed-unit|double-glazed unit}}, and the surface changes how it looks from outside and how it performs." },
    { t: "p", x: "Tints and fritted patterns change appearance as well. A tint absorbs more light and can reduce reflection, but it also makes the glass warmer. A ceramic frit scatters light and can soften reflections. These choices help on a prominent elevation, but they also change the daylight inside. The aim is a balance, not a maximum." },
    { t: "h2", x: "Solar control without a mirror" },
    { t: "p", x: "Reducing {{solar-heat-gain|solar heat gain}} does not always require a highly reflective surface. Shading outside the glass, such as fins, screens or deep returns, keeps sun off the glass before it enters, with no change to the glass appearance. This can allow a clearer, calmer glass choice and a more modest reflection." },
    { t: "p", x: "Where external shading is not possible, compare several glass options with similar solar factor but different reflectance. The differences can be large. The sun-shading options are explained in {{/journal/louvers-and-sun-shading-fins|louvers and sun-shading fins}}. A good consultant will present a few options with their trade-offs in light, heat and appearance." },
    { t: "h2", x: "Safety on roads and around people" },
    { t: "p", x: "Glare matters most where people are making quick decisions: drivers at junctions, pilots on approaches, pedestrians at crossings and neighbours in their homes. A reflection can be uncomfortable or distracting without being dangerous, but it can also create a disability glare that hides objects. Local authorities sometimes ask for limits on reflectance for tall or prominent buildings." },
    { t: "p", x: "Do not wait for a complaint. Early in design, note what is nearby: roads, bends, junctions, tall neighbours, hospitals, schools, flight paths. If any are sensitive, mention them to the {{facade-consultant|facade consultant}} so the glass and the form are considered together. It is much easier to adjust a glass choice on paper than to replace it on a completed building." },
    { t: "h2", x: "Framing, fixing and the whole surface" },
    { t: "p", x: "The look of a glass wall depends on its framing as well. A {{/systems/structural-glazing|structural glazing}} system shows a continuous glass surface with no outside caps, which can make reflections more uniform and mirror-like. A capped system breaks the surface with lines, which can soften the reflection. Neither is right or wrong, but they feel different from outside." },
    { t: "p", x: "Flatness matters too. Heat-treated glass can show slight distortion, and in a strongly reflective wall that distortion shows as waviness in the reflected image. Ask for the flatness standard and view a sample in raking light. The wider coordination between glass and frame is covered in {{/systems/curtain-wall|curtain wall}} design, where sample bays help the team decide." },
    { t: "h2", x: "Curved surfaces, birds and the wider setting" },
    { t: "p", x: "A flat vertical wall is the easiest case to predict. Curved facades are harder, because a concave surface can focus reflected sunlight into a small bright area, sometimes far from the building. Tilted glass, such as a sloping atrium wall or a canopy, can send light down to pavements and vehicles. These shapes deserve a specialist reflection study early, before glass types are fixed." },
    { t: "p", x: "Height changes the picture as well. A tall facade reflects light over a long distance, and it reflects the sky as well as the sun. On a clear day the whole elevation can turn bright. Reflections from tall towers can reach distant roads and other buildings, so the study area should extend beyond the immediate site. Ask who will review the study and what they will do if it shows a problem, because a finding is only useful if someone has the authority to change the glass, the shape or the shading in response." },
        { t: "p", x: "Reflective glass raises other issues beyond glare. Birds can mistake a reflected sky or tree for open space and strike the glass. Patterns such as ceramic frit or markers on the outer surface make glass visible to them. If the site is near trees, water or open land, discuss this with the consultant and the client." },
    { t: "p", x: "The neighbours also see the building as a whole. A very reflective wall can change the feeling of a street, making it hotter, brighter or more exposed, and can look out of place beside a modest context. Appearance is a legitimate design question. Show the neighbours and the approving authority a large sample or a rendering based on real glass data, rather than a generic image. Early conversation is usually kinder than a complaint after the scaffold has come down, and it gives the design team time to adjust." },
    { t: "h2", x: "Keeping records and matching later" },
    { t: "p", x: "Coated glass can vary slightly between production runs, so keep a signed sample, the full specification and the supplier data. When a pane breaks years later, the replacement should match in colour and reflectance. Without records, a patch of different glass can be as visible as the original glare problem, especially on a large smooth facade." },
    { t: "p", x: "Include a short note in the handover pack that names the glass, the coating surface and the supplier references. Ask the supplier how long the product is expected to remain available, and discuss a small stock of spare panes for the most exposed positions. The same careful record keeping helps with maintenance, inspection and any later warranty discussion." },
    { t: "h2", x: "What to check before you specify" },
    { t: "ol", items: [
      "Ask for outside reflectance alongside light transmittance and solar factor.",
      "View a large sample outdoors, in the morning, noon and evening sun.",
      "Map nearby roads, windows and sensitive uses that the facade faces.",
      "Consider external shading to reduce the need for a highly reflective glass.",
      "Request a reflection study for curved, tilted or very prominent facades.",
      "Confirm any local authority limits on reflectance early in the design.",
    ] },
    { t: "p", x: "Approve the final glass on a full-size {{mock-up|mock-up}} wherever practical, since the colour and reflection of a large installed wall differ from a hand sample. Keep records of the approved sample, so later replacement panes match. Put these points in the brief at the start, so every bidder prices the same scope and nobody discovers a missing requirement after the order has been placed." },
    { t: "note", x: "This guidance is general. Reflectance limits, glass build-ups and any reflection studies are confirmed per project with the facade consultant and the approving authority." },
  ],
};

export default article;
