import type { Article } from "../journal";

const article: Article = {
  slug: "low-e-coatings-explained-for-facades",
  title: "Low-e coatings explained for facades",
  seoTitle: "Low-E Coatings Explained for Facades",
  description: "What a low-e coating does on facade glass, which surface of a double-glazed unit it sits on, and what to ask a supplier before you specify it.",
  excerpt: "A low-e coating is a thin layer on glass that changes how heat radiates through it. Where it sits and which type you choose decide whether it helps your building.",
  teaser: "A thin layer on glass that changes how heat moves. Where it sits matters.",
  topic: "Performance",
  date: "2026-10-08",
  hero: "lowe-hero",
  card: "lowe-card",
  og: "/og/curtain-wall.jpg",
  terms: ["low-e-coating", "solar-heat-gain", "u-value"],
  systems: ["curtain-wall", "casement-windows"],
  faq: [
    {
      question: "What does a low-e coating do on facade glass?",
      answer: "A low-e coating is a very thin, nearly invisible layer that reflects heat radiation. In a double-glazed unit it reduces heat flow through the glass, and some versions also reduce the sun's heat entering. The type and the surface it sits on decide which of those jobs it does.",
    },
    {
      question: "Which surface of the glass should the low-e coating be on?",
      answer: "It depends on the goal. Coatings aimed at reducing solar heat usually sit on a surface facing the sealed gap, towards the outside pane. Coatings aimed at insulation sit elsewhere. Surfaces are counted from the outside, so the specification must state the surface number clearly.",
    },
    {
      question: "Does low-e glass make a room darker?",
      answer: "Some coatings reduce visible light and some change the tint slightly, while others are almost clear. There is always a balance between daylight, solar control and appearance. Ask for performance figures and judge a large sample in daylight before approving a coated glass for a whole elevation.",
    },
    {
      question: "Can a low-e coating be added to existing windows?",
      answer: "Factory coatings are applied inside the glass manufacturing process and cannot be copied on site. Retrofit films exist, but they behave differently and can affect warranty and glass stress. For existing buildings, ask the facade consultant to assess the glass and frame before choosing any retrofit.",
    },
  ],
  body: [
    { t: "p", x: "Most people who specify glass have heard the phrase low-e, and many assume it simply means better glass. It is more specific than that. A low-e coating is a very thin layer, invisible to most people at normal viewing distance, applied to a surface of the glass. Its job is to change how heat radiates across the glazing. Whether it helps your building depends on the climate, the orientation and where in the unit the coating is placed. This article explains the idea in plain terms." },
    { t: "h2", x: "What the coating actually does" },
    { t: "p", x: "Heat moves through glass in three ways: by conduction through the material, by convection in the air next to it, and by radiation, which is heat travelling as invisible light. Ordinary glass is poor at stopping that radiation. A {{low-e-coating|low-e coating}} is a thin metallic or metal-oxide layer that reflects much of the long-wave heat radiation back towards where it came from, while letting visible light pass. The word low-e stands for low emissivity, meaning the surface gives off little radiant heat." },
    { t: "p", x: "Because the layer works on radiation, it matters most when the glass is part of a {{double-glazed-unit|double-glazed unit}}. Inside a sealed gap, the coating cuts the radiant exchange between the two panes. That improves the insulation of the whole unit and is reflected in a lower {{u-value|U-value}}. On a single pane, the coating has far less to work with, and it can also be delicate, so facade glass that carries one is usually inside a sealed unit." },
    { t: "h2", x: "Two jobs: keeping heat in and keeping sun out" },
    { t: "p", x: "A coating can be tuned for different priorities, and this is where specifications often go wrong. One family is designed mainly to improve insulation. It lets a large share of the sun's energy pass while reducing heat loss, which suits cold climates and heated buildings. Another family is designed for solar control. It admits daylight but reduces how much of the sun's energy becomes heat inside, which is the priority for most air-conditioned buildings in hot, sunny regions." },
    { t: "p", x: "The figure that describes the second job is the {{solar-heat-gain|solar heat gain}} of the glass, often given as a solar factor, g-value or SHGC. A building with large glazed elevations in a hot climate will usually care more about this than about insulation alone. A building in a cooler hill region may care about both. The honest brief is not simply to ask for low-e, but to state which problem you are trying to solve and let the facade consultant choose accordingly." },
    { t: "img", id: "lowe-1", cap: "The same glass unit can behave very differently depending on which surface carries the coating." },
    { t: "h2", x: "Which surface the coating sits on" },
    { t: "p", x: "A double-glazed unit has four surfaces, numbered from the outside: the outer face of the outer pane is one, the face towards the gap is two, the gap-facing surface of the inner pane is three, and the inner face of the inner pane is four. Coatings sit on faces inside the sealed unit, which protects them from cleaning and weather. A solar control coating is usually placed on the gap side of the outer pane, so it rejects heat before it crosses the gap." },
    { t: "p", x: "An insulation-focused coating is more often placed on a different internal surface, so it keeps room heat from radiating outwards. Two units with the same coating on different surfaces can perform differently, and the difference can be large. This is why a specification should name the surface number as well as the coating. A line that only says low-e glass leaves the supplier to decide, and the decision may not match your intent." },
    { t: "h2", x: "The trade-offs: light, colour and reflection" },
    { t: "p", x: "No coating gives something for nothing. Stronger solar control usually means less visible light, a more noticeable tint or higher external reflectance. Weaker solar control keeps the glass clearer and more neutral but lets more heat in. Architects often want a very clear, low-reflection facade with strong solar control, and the available products rarely deliver all three. The practical task is to choose the balance that suits the building and to see it before committing." },
    { t: "ul", items: [
      "Visible light transmittance: how much daylight passes through the unit.",
      "Solar factor: how much of the sun's energy enters as heat.",
      "U-value: how well the unit resists heat flow when there is a temperature difference.",
      "External reflectance: how mirror-like the facade appears from the street.",
      "Colour: the tint seen from outside and the colour rendering seen from inside.",
    ] },
    { t: "p", x: "These figures come from the glass manufacturer for a stated build-up. They describe the glass unit, not the finished window. A frame with a poor thermal performance can pull down the overall result, which is why {{/journal/thermal-breaks-in-aluminium-frames|thermal breaks in aluminium frames}} matter just as much as the glass on a high-performance elevation." },
    { t: "h2", x: "Hard coat and soft coat" },
    { t: "p", x: "Suppliers often describe coatings as hard or soft. A hard coating is applied while the glass is still hot during manufacture and is fairly durable. A soft coating is applied afterwards in a separate process, usually giving higher performance, but it is more delicate and is meant to live inside a sealed unit. Some soft coatings can be heat treated and some cannot, which affects whether they can be used on toughened or heat-strengthened panes." },
    { t: "p", x: "This matters when a facade needs safety glazing or higher strength. A coating that cannot be toughened after coating may need a different route, such as using a coated glass that is made for heat treatment. Ask the supplier to confirm that the coating is compatible with the glass type you intend, whether {{toughened-glass|toughened glass}}, heat-strengthened or laminated. Mixed assumptions here are a common cause of late changes." },
    { t: "h2", x: "Edge deletion, handling and appearance on site" },
    { t: "p", x: "Where a coated pane meets the sealed edge of a unit, the coating is usually removed around the perimeter so the sealant can bond properly to the glass. That detail is handled in the factory, but it affects how the unit is glazed. Frames, gaskets and {{sealant-joint|sealant joints}} should be compatible with the unit edge, and the glazing drawings should show the zone clearly. Poor edge detail can lead to seal failure and misty units later." },
    { t: "p", x: "On site, coated glass needs careful handling. Avoid scraping, stickers placed on the wrong face, and cleaning with abrasive tools. Plaster splashes, grinding dust and welding sparks can mark any glass, and a mark on a coating can be permanent. Keep the protective film or tape that the supplier recommends until close to completion. When glass arrives, check that the coated face and the unit orientation match the approved drawing before installation begins." },
    { t: "h2", x: "Check the whole elevation, not a catalogue figure" },
    { t: "p", x: "A small sample on a desk looks different from a full elevation. Reflection changes through the day, and slight batch variation can show as a patchwork when many panes sit side by side. Ask for a large sample, view it outdoors against the intended frame colour, and agree an acceptance standard for colour uniformity at the start. A full-bay {{mock-up|mock-up}} is the best way to check how coated glass, spandrel and frame read together." },
    { t: "p", x: "Also check how the coating behaves next to {{spandrel|spandrel}} panels. A spandrel is meant to look like the vision glass beside it, and a mismatch can be obvious at certain angles. The same applies to a facade that mixes coated glass from more than one source. For wider context on choosing the glass build-up itself, see {{/journal/choosing-facade-glass|Choosing facade glass}}, and for how this ties to condensation, see {{/journal/condensation-on-windows-and-facades|Condensation on windows and facades}}." },
    { t: "h2", x: "Questions to ask a glass supplier" },
    { t: "ol", items: [
      "What is the full build-up, from outside to inside, and which surface carries each coating?",
      "Is the coating aimed at insulation, solar control, or both, and what figures apply to the unit?",
      "Can the coating be toughened, heat-strengthened or laminated, and in which sizes?",
      "How is the coating removed at the unit edge, and what sealant is compatible?",
      "What colour and reflectance variation should we expect across a large elevation?",
      "How should the glass be stored, handled and cleaned on site?",
    ] },
    { t: "p", x: "Written answers to these questions belong in the submittal package. They help the facade consultant, the contractor and the owner agree what the coating is for before any glass is ordered. That is far cheaper than discovering a mismatch when a full set of coated units has been made." },
    { t: "note", x: "This guidance is general. Coating type, surface, performance figures and applicable standards are confirmed for each project with the facade consultant and the glass supplier." },
  ],
};

export default article;
