import type { Article } from "../journal";

const article: Article = {
  slug: "perforated-metal-screens-on-facades",
  title: "Perforated metal screens on facades: shade, privacy and airflow",
  seoTitle: "Perforated Metal Screens on Facades",
  description: "A perforated metal screen trades shade, privacy, view and airflow. Learn how pattern, open area, finish and fixing shape the result on a facade.",
  excerpt: "A perforated screen can shade a wall, hide services and soften a facade, but every hole pattern trades light, view and air against privacy. Here is how to choose.",
  teaser: "How hole pattern, finish and fixing shape a screen's behaviour.",
  topic: "Cladding",
  date: "2026-10-08",
  hero: "perf-hero",
  card: "perf-card",
  og: "/og/louvers.jpg",
  terms: ["cassette", "anodising", "powder-coating"],
  systems: ["cladding", "louvers"],
  faq: [
    { question: "What is a perforated metal facade screen?", answer: "It is a metal sheet punched or cut with a pattern of holes and fixed in front of a wall, window or service area. It filters sun, view and air, and changes how the building looks by day and by night. The pattern and open area are chosen for the job." },
    { question: "Does a perforated screen reduce heat on a building?", answer: "It can reduce direct sun reaching glass or wall behind it, depending on orientation, pattern and how far it stands from the surface. It is a shading device, not insulation, so a facade consultant should check its effect for your climate and elevation." },
    { question: "Which finish is best for a perforated metal screen?", answer: "Common choices are anodised or powder-coated aluminium. The right finish depends on colour, exposure, edge quality and warranty. Perforated edges expose more metal, so ask the finisher how the holes and cut edges are protected and what the warranty covers." },
    { question: "How are perforated screens fixed to a building?", answer: "Screens are usually folded into panels or cassettes and hung on a support frame fixed to the structure. The frame must allow thermal movement and resist wind, and fixings should be hidden or consistent with the design. Drawings should show every connection." },
  ],
  body: [
    { t: "p", x: "A perforated metal screen is one of the most flexible tools in facade design. It can shade a west wall, hide plant and parking, give a balcony some privacy and lend a plain building a recognisable face. It does all of this with one sheet of metal and a pattern of holes. The difficulty is that the same holes that let in light and air also let in view and rain. This article explains what the pattern, the finish and the fixing control." },
    { t: "h2", x: "What a perforated screen is for" },
    { t: "p", x: "Screens are used for four jobs, often at once. They filter sunlight before it reaches glass, so rooms behind stay calmer. They screen service areas such as plant decks and parking levels while still letting air move. They give privacy to balconies and terraces without turning them into closed boxes. And they give the facade a surface and a pattern that changes with the light." },
    { t: "p", x: "Knowing the main job first prevents wasted drawings. A screen for shade needs different spacing from a screen for privacy, and a screen that hides a ventilated plant area needs enough open area for the equipment to breathe. The same panel will not serve all four. Write the priority down before choosing a pattern, and share it with the {{facade-consultant|facade consultant}}." },
    { t: "h2", x: "Pattern, open area and what you see through it" },
    { t: "p", x: "Open area is the share of the sheet that is hole rather than metal. A higher open area lets in more light, air and view. A lower one gives more privacy and shade but darkens the space behind. The size and spacing of the holes matter as much as the total, because small closely spaced holes read as a soft tone from far away, while large holes read as a pattern of individual openings." },
    { t: "p", x: "View works differently from light. From inside, people look through the holes at a distance, so a screen can feel quite open to occupants while remaining private from outside in daylight. At night the effect reverses when rooms are lit. Test this on a sample rather than trusting a drawing, and look at it from the street and from the room, in daylight and after dark." },
    { t: "img", id: "perf-1", cap: "A screen works by balancing open area against shade, view and privacy, and the balance changes with the hour." },
    { t: "h2", x: "Shade and heat: what a screen can and cannot do" },
    { t: "p", x: "A screen that stands away from the building intercepts direct sun before it hits glass or wall, which can lower {{solar-heat-gain|solar heat gain}} on that elevation. Its effect depends on orientation, sun angle, the pattern and the distance from the surface. A screen on a west face with a low afternoon sun behaves differently from one on a north face. Do not assume one pattern works on every side." },
    { t: "p", x: "A screen is not insulation. It will not stop heat conducting through a wall, and a tight screen can trap warm air against a surface if airflow behind it is poor. Leave enough gap for air to move and for cleaning access. For a deeper treatment of fins and blades, see {{/journal/louvers-and-sun-shading-fins|louvers and sun-shading fins}}, which compares them with perforated sheet." },
    { t: "h2", x: "Metal, thickness and flatness" },
    { t: "p", x: "Aluminium is the usual choice because it is light, can be formed and takes good finishes. The sheet must be thick enough to stay flat after perforation, because removing metal makes it more flexible. Large screens can show waviness in raking light, which is usually called oil-canning. Stiffening folds, edge returns and a sensible panel size reduce it." },
    { t: "p", x: "Perforation is done by punching or cutting, and the tooling leaves a burr or slight distortion at each hole. Ask for samples that show the edge quality and flatness at the proposed thickness. Agree an acceptance standard for flatness and pattern alignment at the start. Pattern continuity across joints is easy to overlook and very visible once panels are on the wall." },
    { t: "h2", x: "Finish: anodised or coated" },
    { t: "p", x: "Perforated sheet has many more edges than plain sheet, and each hole edge is bare metal that the finish must reach. {{anodising|Anodising}} grows a protective layer from the metal itself and gives a metallic look, with colour range limited by the process. {{powder-coating|Powder coating}} gives a wide range of colours and a thicker film, but it can bridge small holes and soften edges if applied heavily." },
    { t: "p", x: "Ask the finisher how hole edges are treated, whether the coating is applied before or after perforation, and what the warranty says about edges and about coastal or polluted air. The comparison of coatings is explained in {{/journal/anodised-powder-coated-or-pvdf|anodised, powder-coated or PVDF}}. Choose the finish with the exposure of the site in mind, and approve a physical sample." },
    { t: "h2", x: "Fixing, frames and movement" },
    { t: "p", x: "Most screens are folded into trays or {{cassette|cassettes}} that hang on a support frame, or fixed as flat panels between rails. The frame needs to carry the weight, resist wind pushing and pulling on a large area, and let the metal expand and contract with temperature. A screen that cannot move will buckle or rattle, and a screen that moves too freely will be noisy in wind." },
    { t: "p", x: "Check that the fixings and spacing appear on the {{shop-drawings|shop drawings}}, including how a panel is removed for cleaning or replacement. Wind loads on a perforated sheet are lower than on a solid one, but they are not zero, and edges and corners usually see the highest suction. The designer should confirm the loads and the anchor design for the actual building height and exposure." },
    { t: "h2", x: "Cleaning, access and daily use" },
    { t: "p", x: "A screen collects dust and leaves like any outdoor surface, and the pattern can make cleaning slower. Think about how people will reach it. A screen in front of windows should allow window cleaning without damaging the finish. Consider whether birds could nest behind it and whether the gap needs mesh or a detail that prevents it." },
    { t: "p", x: "Sound and light are everyday details too. Loose panels can hum in wind, and a bright finish can reflect light into neighbouring rooms. Include these in the sample review. A short written cleaning and inspection routine, handed over with the building, helps the screen stay presentable. The general routine is covered in the {{/journal/facade-maintenance-checklist|facade maintenance checklist}}." },
    { t: "h2", x: "Airflow, rain and the building behind" },
    { t: "p", x: "A screen in front of a plant deck or a car park is partly a ventilation device. The open area must be large enough that equipment behind it can draw and discharge air without recirculating, and the designer of that equipment should confirm the requirement. A screen that looks open on a drawing can become restrictive once panel folds, stiffeners and frames are added." },
    { t: "p", x: "Rain is another point. A perforated sheet is not a weatherproof layer, so whatever sits behind it must be protected by its own wall or window. Water will pass through the holes, run down the back face and drip from the lower edge, which can stain the facade or the walkway below. Ask for a drip detail and think about what the water lands on." },
    { t: "p", x: "Light and view need the same care at night. Lit rooms behind a screen show their lights through the holes, which can be attractive or intrusive. Some designs use the screen as a diffuser for deliberate lighting. If that is the aim, agree the lighting position and the pattern together, because the screen cannot be changed cheaply once panels are made. A small test panel lit from behind is a cheap way to see the effect, and it can also show how the holes line up across a joint." },
    { t: "h2", x: "Questions to settle before ordering" },
    { t: "ul", items: [
      "What is the main job of the screen: shade, privacy, concealment or appearance?",
      "What open area and hole pattern give the right balance, tested on a sample?",
      "Which metal, thickness and stiffening keep the panel flat?",
      "How are hole edges finished, and what does the warranty cover?",
      "How is each panel fixed, moved for thermal change and replaced?",
      "How will the screen be cleaned and inspected after handover?",
    ] },
    { t: "p", x: "The answers feed directly into the {{/systems/cladding|cladding}} and {{/systems/louvers|louvre}} packages, so share them when you ask a manufacturer for a proposal. A full-bay {{mock-up|mock-up}} is the best way to judge shade, view and finish together before committing the whole elevation." },
    { t: "note", x: "This guidance is general. Pattern, open area, thickness, finishes, loads and fixing details are confirmed per project with the facade consultant." },
  ],
};

export default article;
