import type { Article } from "../journal";

const article: Article = {
  slug: "pergolas-and-glass-canopies-weather-and-drainage",
  title: "Pergolas and glass canopies: weather and drainage",
  seoTitle: "Pergolas and Glass Canopies",
  description: "Pergolas and glass canopies live in the weather. How rain, wind and heat shape the design, where water must go, and what to check before ordering.",
  excerpt: "A pergola or glass canopy is exposed on every side. Getting the drainage, glazing and fixings right matters more than the shape.",
  teaser: "Where the water goes decides whether a canopy lasts.",
  topic: "Elements",
  date: "2026-10-08",
  hero: "pergola-hero",
  card: "pergola-card",
  og: "/og/pergolas.jpg",
  terms: ["pergola", "drainage-slot", "glazing"],
  systems: ["pergolas", "skylights"],
  faq: [
    {
      question: "How does a glass canopy drain rainwater?",
      answer: "The roof is sloped so water runs to a gutter, a drainage channel or an edge, and from there to a downpipe or a safe discharge point. Glazing joints and aluminium sections have their own drainage paths. The slope, outlets and overflow route must be designed, not left to chance.",
    },
    {
      question: "What glass is used for canopies and overhead glazing?",
      answer: "Overhead glazing is normally laminated, so that a broken pane stays in place and does not fall. It may also be toughened or heat-strengthened, and often double-glazed where heat matters. The facade consultant specifies the build-up, since the applicable code and the use of the space both affect it.",
    },
    {
      question: "Does a pergola need drainage?",
      answer: "An open louvred pergola still collects rain on its roof members, and the water has to go somewhere. Many designs channel it through the frame to hidden outlets. The frame's drainage path, the slope and the outlets should be shown on the drawings and checked at the sample.",
    },
    {
      question: "Why do canopy glass joints leak?",
      answer: "Common causes include a slope that is too shallow, blocked outlets, worn gaskets, poorly formed sealant joints, or movement the joints cannot absorb. Wind-driven rain makes weak details show up. A leak should be traced to its path before it is sealed.",
    },
  ],
  body: [
    { t: "p", x: "Most of a building facade is vertical, and rain mostly runs down it. A pergola or a glass canopy is different. It is a roof, and often a roof with a very light structure, glass that has to stay clear, and joints that face the sky. Water sits on it, runs along it and looks for any gap. Wind lifts it. The sun heats it. This article explains what that means for design and what to check before you order." },
    { t: "h2", x: "A canopy is a small roof" },
    { t: "p", x: "It helps to think of a canopy the way you would think of a roof. It needs a slope so that water runs off rather than lying on the surface. It needs gutters or channels to collect the flow. It needs outlets and a safe place for the water to go. And it needs an overflow route for the day the main outlets are blocked or overwhelmed." },
    { t: "p", x: "A pergola is similar even if it looks open. Louvres or slats shed water onto beams, which carry it to the posts or to edge channels. If the frame is designed to hide the drainage inside the sections, the outlets must still exist and be reachable. A path that is invisible is also easy to forget about at the first cleaning." },
    { t: "p", x: "A canopy also behaves differently from a wall because rain does not just fall straight down. Wind drives it sideways and upward under the edges, and spray can bounce off the surface below. The edge details, the underside and the point where the canopy meets the building all need to cope with water arriving from more than one direction." },
    { t: "p", x: "Where the canopy meets a wall, the junction is the most vulnerable point. Water running down the wall lands on the canopy, and water running off the canopy must not creep back into the wall. A flashing, a channel or a carefully detailed upstand is normally needed, and it must be coordinated with the wall finish. This is where leaks often begin, well away from the glass." },
    { t: "h2", x: "Slope and the problem of standing water" },
    { t: "p", x: "A glass canopy that is nearly flat may look neat, but standing water carries dust and leaves, stains the glass and loads the joints. A modest slope helps rain flush the surface and carries dirt to the edge. The slope required depends on the system, the glass size and the joints, and is set in the approved drawings, not guessed." },
    { t: "p", x: "Check the slope in the as-built structure. Steelwork that is slightly out of level can leave a pocket where water collects. Agree tolerances with the structure builder, and survey the supporting frame before the glass or the roof members are fixed." },
    { t: "img", id: "pergola-1", cap: "A canopy sheds water only if the slope, the channel and the outlet are designed as one path." },
    { t: "h2", x: "Drainage paths inside the frame" },
    { t: "p", x: "Aluminium canopy and pergola sections usually carry water along their own channels. A {{drainage-slot|drainage slot}} lets water leave a chamber or pocket and return to the outside. These small openings are easy to block with sealant, paint, dust or debris, and easy to overlook when the structure is finished." },
    { t: "ul", items: [
      "Ask for a drawing that shows where water enters, travels and leaves the frame.",
      "Confirm the outlets are kept clear by the installer and the painter.",
      "Make sure water leaving the frame does not run onto a wall or window it can stain.",
      "Check that gutters and downpipes can be reached for cleaning.",
      "Provide an overflow so that a blocked outlet does not flood the interior side.",
    ] },
    { t: "p", x: "Our article on {{/journal/window-drainage-and-weep-holes|window drainage and weep holes}} explains the same principle in a window frame: a designed route that must not be sealed by instinct." },
    { t: "p", x: "Test the drainage before it is hidden. Once ceilings, cladding or soffits are fitted, a blocked outlet or a reversed fall is very hard to correct. Where possible, run water over the finished roof and watch where it goes before the trades that follow close it in. It is a simple check that takes little time and often finds a problem that would otherwise appear in the first monsoon." },
    { t: "h2", x: "Glass for overhead use" },
    { t: "p", x: "Glass above people's heads has a more serious failure mode than glass in a wall. If a pane breaks, it could fall. For that reason, overhead {{glazing|glazing}} is normally laminated, so the pieces are held by the interlayer. It may also be toughened or heat-strengthened, and double-glazed where heat or sound is a concern." },
    { t: "p", x: "The build-up is set by the facade consultant, taking in the use of the space, the span, the loads and the applicable code. Read {{/journal/choosing-facade-glass|choosing facade glass}} for the main types. Skylights have comparable concerns, and the {{/systems/skylights|skylights}} page covers them. Think also about solar heat: a large glass roof can warm the space below, so coatings, tints or shading may be needed." },
    { t: "p", x: "Heat is part of the experience too. A glass canopy over a seating area can trap warmth and glare, and a solid or louvred pergola can offer shade but also hold heat beneath it. Choose between clear, tinted, coated or shaded options by thinking about who sits under it and at what time of day. Adjustable louvres can help, but they add moving parts that need drainage and care." },
    { t: "h2", x: "Wind, uplift and fixings" },
    { t: "p", x: "A canopy is exposed to wind from above and below. Pressure pushes down on the top surface, but suction under the roof and at the edges can lift it. Fixings, brackets and the supporting structure must resist both. The design wind load for a canopy is usually set separately from a wall, because the shape and exposure differ." },
    { t: "p", x: "The attachment to the building is critical. Check what the canopy is fixed to, what that structure can carry, and how the fixing is protected from water. A bracket cut into a wall without proper flashing becomes a leak path into the building. See {{/systems/pergolas|pergolas}} for the system background." },
    { t: "h2", x: "Joints, movement and the sun" },
    { t: "p", x: "Aluminium and glass expand and contract with temperature, and a canopy in full sun sees large swings. Joints must absorb that movement without tearing or pumping water inward. Fixed joints in the wrong place are a common source of cracks and leaks. Read {{/journal/movement-joints-in-facades|movement joints in facades}} for the principles." },
    { t: "p", x: "The finish on the frame also matters in exposed conditions. A pergola faces sun, rain and dust all day, so ask about the finish system and how it will weather. Our article on {{/journal/anodised-powder-coated-or-pvdf|anodised, powder-coated or PVDF finishes}} helps compare options." },
    { t: "p", x: "Noise is a small but real matter. Rain on a glass or metal roof can be loud, and thin members can drum in the wind. If the canopy covers an entrance or a seating area, ask how the design limits rattling and whether the glazing or the fixings can be arranged to reduce it." },
    { t: "p", x: "Finally, think about what happens at the edges of the canopy: dripping onto a walkway, splashing on a door, or running down a column in a way that stains it. A drip edge, a hidden gutter or a downpipe in a sensible position keeps the water away from where people walk and where finishes can be damaged." },
    { t: "h2", x: "Cleaning, maintenance and access" },
    { t: "p", x: "A canopy collects leaves, bird droppings, dust and monsoon silt. Regular cleaning keeps the glass clear and the drains open. Plan how people will reach the roof safely. A canopy with no safe access is likely to be cleaned rarely, and a canopy that is cleaned rarely is more likely to leak." },
    { t: "ul", items: [
      "Clear gutters and outlets before the monsoon and after storms.",
      "Wash glass with methods approved by the supplier, avoiding abrasives.",
      "Inspect sealant joints and gaskets for cracks or gaps.",
      "Check fixings and brackets for looseness or corrosion.",
      "Record any repeated leaks and trace the cause before resealing.",
    ] },
    { t: "p", x: "Ask to see a sample section before the order is placed. It should show the glazing seat, the drainage channel, the finish and the fixing as they will actually be built. A real section answers more questions in a few minutes than a page of descriptions, and it gives the architect and the maintenance team something concrete to comment on." },
    { t: "h2", x: "Questions to ask before you order" },
    { t: "ol", items: [
      "What slope is proposed, and how is it confirmed on site?",
      "Where does the water go, and what is the overflow route?",
      "What glass build-up is proposed, and why?",
      "What wind load and uplift has the design considered?",
      "How is the canopy fixed to the building, and how is that point sealed?",
      "Who maintains it, and how is the roof reached safely?",
    ] },
    { t: "note", x: "This guidance is general. Slopes, glass build-ups, wind loads, standards and details are confirmed per project with the facade consultant." },
  ],
};

export default article;
