import type { Article } from "../journal";

const article: Article = {
  slug: "sealants-and-gaskets-in-facades",
  title: "Sealants and gaskets in facades: what each one does",
  seoTitle: "Sealants and Gaskets in Facades",
  description: "Sealants and gaskets both keep weather out of a facade, but they work differently. Where each is used, how they fail, and what to check on site.",
  excerpt: "Sealants and gaskets are the soft parts of a hard facade. They look minor, yet they carry much of the weather resistance, and they age faster than the metal and glass around them.",
  teaser: "The soft parts of a hard facade: what each does and how they age.",
  topic: "Elements",
  date: "2026-10-08",
  hero: "sealant-hero",
  card: "sealant-card",
  og: "/og/rain-screen-facade.jpg",
  terms: ["sealant-joint", "gasket", "epdm"],
  systems: ["curtain-wall", "rain-screen-facade"],
  faq: [
    {
      question: "What is the difference between a sealant and a gasket in a facade?",
      answer: "A sealant is applied wet into a joint and cures in place, so it takes the shape of the gap and bonds to its sides. A gasket is a pre-formed strip, usually rubber, that is fitted into a profile and works by staying compressed. Each suits different joints and movements.",
    },
    {
      question: "How long do facade sealants last?",
      answer: "There is no single figure. Life depends on the sealant type, the joint design, sunlight, movement, cleaning and the quality of preparation. Sealants are treated as parts that will be inspected and eventually replaced, so the facade should be designed to allow access for that work.",
    },
    {
      question: "Can I seal over an old sealant joint?",
      answer: "Usually not. New sealant often fails to bond to old material and can trap water. The normal method is to cut out the old sealant, clean and prime the joint faces, and re-seal with a compatible product to a method approved by the facade consultant or the system supplier.",
    },
    {
      question: "Why do gaskets shrink or crack on facades?",
      answer: "Rubber gaskets age from sunlight, heat and stress, and a poorly cut or stretched gasket can pull back at the corners. Good installation leaves the gasket slightly generous and bonds the corners. Material choice, such as EPDM, and correct fitting both affect long-term performance.",
    },
  ],
  body: [
    { t: "p", x: "A facade is mostly made of hard things: aluminium, glass, stone and steel. Yet the thing that most often decides whether it keeps rain out is soft. Sealants and gaskets fill the joints between those hard parts, and they work by being slightly flexible. They also age faster than the parts around them. Knowing what each does helps you read a drawing, ask better questions of a supplier, and recognise problems early." },
    { t: "h2", x: "Two different ways to close a gap" },
    { t: "p", x: "A {{sealant-joint|sealant joint}} is closed with a paste that is applied wet, cures into a flexible solid and bonds to the surfaces on each side. It takes the shape of whatever gap it is placed in, so it suits joints where the size varies a little. A {{gasket|gasket}} is a pre-formed strip, usually rubber, with a profile designed to fit a channel in the frame. It does not bond. It works because it stays squeezed between two surfaces." },
    { t: "p", x: "This difference drives most design decisions. A sealant must stick, so surface preparation matters greatly. A gasket must stay compressed, so the dimensions of the channel and the glass or panel matter greatly. Neither is a substitute for the other. A good facade uses each where its behaviour is the right match, and uses drainage and ventilation behind them so that water which passes the outer line has somewhere to go." },
    { t: "h2", x: "Where gaskets are used" },
    { t: "p", x: "Gaskets appear wherever a frame holds glass or a panel and the element is installed in a controlled factory or workshop way. In a {{/systems/curtain-wall|curtain wall}}, they line the glazing pockets and sit between the glass and the pressure plate or glazing bead. In windows, they seal the opening leaf against its frame. They are also used between frame members, as breather or wedge strips, and in sliding and fold doors as brush or pile seals." },
    { t: "p", x: "The most common material in external frame glazing is {{epdm|EPDM}}, a synthetic rubber chosen for its resistance to sunlight, ozone and temperature changes. Other materials are used for specific roles, such as a firm foam strip behind a joint or a softer seal on an opening leaf. The material, hardness and profile are part of the system design, and the supplier's drawings should show them rather than leaving them to the installer." },
    { t: "img", id: "sealant-1", cap: "A gasket works by staying compressed, while a sealant works by bonding to both sides of a joint." },
    { t: "h2", x: "Where sealants are used" },
    { t: "p", x: "Sealants close the joints that cannot be formed by a rubber profile. These include the perimeter joint between a window or curtain wall and the building structure, joints between cladding panels, and the joints at corners where frames meet. In {{structural-glazing|structural glazing}}, a special {{structural-silicone|structural silicone}} also carries load, which makes the quality of application a structural matter, not only a weather matter." },
    { t: "p", x: "Weather sealants are chosen for their ability to move with the joint without tearing or letting go. The joint itself is designed with a depth and width suited to the expected movement, with a backing rod behind the bead so the sealant does not bond on three sides. A joint that is too narrow for the movement, or filled too deep, will fail early no matter how good the product is." },
    { t: "h2", x: "Why preparation decides the result" },
    { t: "p", x: "Most sealant failures are failures of bond, not of the sealant itself. The surfaces must be clean, dry and free of dust, oil, release agents and protective tape residue. Some surfaces need a primer, and some finishes, such as certain coatings or films, need a compatibility check before any sealant touches them. A joint sealed in a hurry on a damp morning is the classic source of a leak that appears later." },
    { t: "ol", items: [
      "Check that the joint size matches the drawing and the expected movement.",
      "Clean both faces and remove loose material, dust and old residue.",
      "Apply primer where the sealant supplier requires it, and allow it to dry.",
      "Fit the backing rod to the correct depth without puncturing it.",
      "Apply the sealant continuously and tool it to a firm contact with both faces.",
      "Remove masking tape promptly and record the batch and date.",
    ] },
    { t: "p", x: "A short adhesion test on a sample joint is a sensible way to confirm compatibility between the sealant, the metal finish and any other material it will touch. The facade consultant can specify what to test and how to record it." },
    { t: "p", x: "Weather on the day also matters. Sealant should not be applied in rain, on a wet surface or when the temperature is outside the range the supplier allows. Work done from a hanging platform or a cradle is especially exposed to wind and dust, so the sequence should leave enough time for cleaning and priming between steps. Supervisors should record the conditions, the batch of material and the person responsible for each run, so any later problem can be traced to a cause." },
    { t: "p", x: "Cure time is another point that is easy to overlook. A bead may skin over within hours yet take far longer to reach full strength, and disturbing it during that period, by cleaning, pushing or loading the joint, can damage the bond. The supplier's data sheet states the conditions and the waiting time before the joint is exposed to full movement or pressure, and the programme should respect it." },
    { t: "h2", x: "Compatibility: the hidden problem" },
    { t: "p", x: "Different soft materials do not always get along. A sealant can stain stone or discolour a neighbouring material, and certain products can attack a gasket or a spacer in a double-glazed unit if they are chemically incompatible. For this reason, the glass supplier, the frame supplier and the sealant supplier should each confirm in writing that their products are compatible with the others." },
    { t: "p", x: "Compatibility also applies to finishes. A sealant bead meeting a powder-coated, anodised or PVDF-coated surface may behave differently on each. If a facade uses several finishes, ask which ones have been checked. Our article on {{/journal/anodised-powder-coated-or-pvdf|anodised, powder-coated or PVDF finishes}} gives background on why those surfaces differ." },
    { t: "h2", x: "How these parts age and fail" },
    { t: "p", x: "Sunlight, heat, cold, cleaning agents, dirt and constant small movement all work on soft parts. Sealants can harden, lose adhesion, split or stain. Gaskets can shrink, harden or pull back at corners. None of this means the facade is faulty. It means these are service items, and a maintenance plan should assume they will be inspected and sometimes renewed." },
    { t: "ul", items: [
      "Cracks or splits in a sealant bead, especially at joint ends and corners.",
      "A sealant that has pulled away from one face, leaving a visible gap.",
      "A gasket that has shrunk back from a corner or looks hard and brittle.",
      "Staining or streaking below a joint, which can signal water or migration.",
      "Soft or sticky sealant long after the expected cure time.",
    ] },
    { t: "p", x: "Early repair is far cheaper than late repair. A short section re-sealed after a monsoon season is a minor task, whereas a joint left open can let water into a wall cavity for years. Our guide to the {{/journal/facade-maintenance-checklist|facade maintenance checklist}} suggests how to inspect joints routinely." },
    { t: "h2", x: "Design details that help the soft parts last" },
    { t: "p", x: "The best sealant joint is one that is not asked to do everything. Good facade design provides a drained and ventilated second line behind the outer seal, so a small leak at the surface does not become a wet interior. Joints should be accessible for repair, with enough clearance to cut out and re-seal, and the design should avoid placing a joint where water pools or where the sealant is exposed to constant abrasion." },
    { t: "p", x: "For gaskets, the lesson is to keep them out of tension. They should be fitted with slight excess length at corners rather than stretched, and the corners should be joined or bonded as the system supplier directs. Where a rain-screen sits in front of the wall, the joints between panels follow different rules, which are covered in {{/journal/rain-screen-cladding-the-gap|rain screen cladding: the gap}}." },
    { t: "h2", x: "What to ask before you approve" },
    { t: "ul", items: [
      "Which sealant and gasket materials are proposed, and where does each one go?",
      "Has compatibility with the glass, finishes and adjacent materials been confirmed in writing?",
      "What is the joint size, the backing detail and the expected movement?",
      "What surface preparation and adhesion testing will be done on site?",
      "How will the joints be inspected, and how can they be renewed later?",
    ] },
    { t: "p", x: "Sealants and gaskets rarely feature in sales brochures, but they are where many leak investigations end. Asking about them early, and seeing them on a mock-up, is a low-cost way to avoid later disputes." },
    { t: "note", x: "This guidance is general. Materials, joint sizes, preparation methods and test requirements are confirmed for each project with the facade consultant and the system supplier." },
  ],
};

export default article;
