import type { Article } from "../journal";

const article: Article = {
  slug: "structural-and-deflection-tests-for-facades",
  title: "Structural and deflection tests for facades: what they measure",
  seoTitle: "Facade Structural and Deflection Tests",
  description: "What a structural load test on a facade actually measures: wind pressure, deflection, permanent set and safety margin, and how to read a report.",
  excerpt: "A structural test loads a full-size facade sample with pressure and records how far it moves. Knowing what each reading means helps you read a report without being misled.",
  teaser: "What a facade load test measures, and how to read the report.",
  topic: "Testing",
  date: "2026-10-08",
  hero: "structest-hero",
  card: "structest-card",
  og: "/og/curtain-wall.jpg",
  terms: ["astm-e330", "deflection", "wind-load"],
  systems: ["curtain-wall"],
  faq: [
    {
      question: "What does a structural test on a curtain wall measure?",
      answer: "It applies a controlled pressure to a full-size sample, in and out, and records how far the frame and glass move under load. It also checks whether anything is permanently deformed or damaged afterwards. The specification sets the pressure and the movement limits, and the report states what was applied.",
    },
    {
      question: "What is deflection in a facade and why does it matter?",
      answer: "Deflection is how far a member bends under load. Too much movement can overstress glass, open sealant joints, damage gaskets or cause visible distortion. Limits are set in the specification by the facade consultant, and they differ for the frame, the glass and the supporting structure.",
    },
    {
      question: "What is the difference between a design load and a test load?",
      answer: "The design load is the wind pressure the facade is expected to resist in service, taken from the project's wind data and the applicable code. The test load is the pressure applied in the laboratory, usually the design load first and then a higher proof load, as the specification requires.",
    },
    {
      question: "Does a passed facade test mean the whole building is safe?",
      answer: "No. A test describes the sample that was tested, built the way it was built. The installed facade, its anchors and the slab edges must match that sample and be checked separately. A report is evidence for one assembly, not a guarantee for every condition on the building.",
    },
  ],
  body: [
    { t: "p", x: "Wind does not push on a facade gently or evenly. It presses inward on one face of a building, pulls outward on another, and gusts across corners and the top edges. A facade has to take that pressure, pass it into the structure and stay in one piece, without moving so much that glass cracks or seals open. A structural test is the way a specification checks that a particular assembly can do this. It is a measurement exercise, and the numbers only make sense when you know what was measured." },
    { t: "h2", x: "Start with the load the facade must resist" },
    { t: "p", x: "Every structural test begins with a {{wind-load|wind load}}. This comes from the site, the height of the building, the surrounding terrain, the shape of the facade and the applicable national code. Corners and parapet zones usually see higher suction than the middle of a wall, so a single building can have more than one design pressure. The facade consultant sets these values in the specification, and the manufacturer designs the frame, glass and anchors to meet them." },
    { t: "p", x: "It helps to separate three ideas. The design load is what the facade is expected to resist in service. The test load is what a laboratory applies to a sample, which may be the design value and then a higher proof value. The calculation is the engineering check that sits behind both. A test report that quotes a pressure without saying where the number came from is hard to use." },
    { t: "h2", x: "What a laboratory test actually does" },
    { t: "p", x: "The standard method most often named for static pressure testing is {{astm-e330|ASTM E330}}. In plain terms, a full-size sample of the facade is fixed into a test chamber. Air is then pumped in or drawn out to create a steady pressure difference across it, first pushing inward and then pulling outward. Instruments record how far chosen points on the frame and glass move at each stage." },
    { t: "p", x: "The point of the method is to show how a real assembly behaves, not how a drawing predicts it. It measures movement under a stated pressure and whether the sample comes through undamaged. It does not, by itself, say anything about water leakage or air leakage. Those are separate tests on the same sample, described on our {{/testing|testing page}} and in {{/journal/what-astm-e331-tests|what ASTM E331 tests}}." },
    { t: "img", id: "structest-1", cap: "A structural test records how far a loaded sample moves, then whether it returns to where it started." },
    { t: "h2", x: "Deflection: how far is too far" },
    { t: "p", x: "{{deflection|Deflection}} is the amount a member bends under load. A mullion in a curtain wall behaves like a long beam fixed at its ends, and wind makes it bow. A small bow is normal and harmless. A large one can overstress glass edges, squeeze sealant joints, pinch gaskets or make reflections ripple across the elevation." },
    { t: "p", x: "Limits are normally expressed as a fraction of the span, and different parts have different limits. The frame, the glass in its pocket and the supporting slab all move, and the specification should say which limit applies to which. Be careful when a report quotes movement without naming the member measured. A figure taken at mid-span of a mullion says something quite different from one taken at a corner." },
    { t: "h2", x: "Permanent set and the proof load" },
    { t: "p", x: "A frame that springs back after a load is behaving elastically. A frame that stays slightly bent has been pushed past that point. The residual movement left after the pressure is released is often called permanent set, and specifications usually limit it. This is why a higher proof load is applied after the design load: to see whether the assembly keeps a margin beyond its working condition." },
    { t: "p", x: "Pay attention to the order of events in a report. Which pressure was applied first? How long was each pressure held? Were readings taken before, during and after? Did anything crack, slip, loosen or open? A clear report lists these steps and states what was observed at each. A report that only says 'passed' with no readings is evidence of very little." },
    { t: "h2", x: "What a test report should show" },
    { t: "p", x: "A usable report describes the sample so that someone could build another one like it. It should be possible to compare it with your project drawings line by line." },
    { t: "ul", items: [
      "The profile system, member sizes and spacing used in the sample.",
      "The glass build-up, the glazing method and the sealant or gasket type.",
      "Anchor type and fixing details at the sample's edges.",
      "The pressures applied, the direction, the hold time and the order.",
      "The points where movement was measured, and the readings recorded.",
      "Any visible damage, permanent set or change in the sample after loading.",
      "The date, the laboratory and the standard the method followed.",
    ] },
    { t: "p", x: "If your project uses a bigger span, a thicker glass, a different anchor or a different mullion than the sample, the report does not automatically cover it. Ask the manufacturer to show where the project differs from the tested assembly, and how that difference has been checked by calculation or additional testing." },
    { t: "p", x: "Ask also about the test setup. A sample fixed into a rigid chamber behaves differently from a facade fixed to a flexing slab edge. If the real building has long cantilevered slabs or movement at the structure, the report alone does not show how the facade will cope. The facade consultant should say how the tested boundary conditions compare with the real ones, and whether the anchors have been designed for the movement the structure will actually impose." },
    { t: "p", x: "Glass deserves its own attention. Glass is brittle, so it cannot absorb overload by bending the way a metal section can. A report should state the glass build-up, its support on all edges and the movement recorded at its centre. Glass that moves more than its pocket and sealant can tolerate may stay intact in the test and still fail later through slow edge damage. That is why the glazing clearances and setting arrangement are as relevant as the pressure value." },
    { t: "h2", x: "Calculation, test and mock-up work together" },
    { t: "p", x: "Most projects use a combination. Engineering calculations establish member sizes early, so that shop drawings can be prepared. A laboratory test on a representative sample then confirms that the assembly behaves as the calculation expected. A site {{mock-up|mock-up}} follows, showing how the real details, tolerances and installers perform on the actual building." },
    { t: "p", x: "None of these replaces the others. A calculation can miss a poor fixing. A laboratory sample is built under ideal conditions by skilled hands. A mock-up shows workmanship but is rarely loaded to failure. Treat them as three views of the same facade, and ask the facade consultant which are required on your project and in what order. Our article on {{/journal/facade-mock-up-review|reviewing a facade mock-up}} describes what to look at on site." },
    { t: "h2", x: "Common ways reports mislead" },
    { t: "p", x: "Most problems arise from the gap between what was tested and what will be built. Watch for a few patterns." },
    { t: "ul", items: [
      "A sample that is smaller, simpler or stiffer than the real facade.",
      "A tested glass thickness that is thicker than the glass on your drawings.",
      "A report from a different profile series from the same manufacturer.",
      "Movement limits quoted without saying which member or point they apply to.",
      "A pass that depends on anchors or slab edges not shown in your design.",
      "A report with no date, no laboratory name or no stated method.",
    ] },
    { t: "p", x: "None of these means the facade is unsafe. They mean the report cannot yet be used as evidence for your project, and the missing link needs to be closed before the design is approved." },
    { t: "h2", x: "Questions to ask before you accept a test" },
    { t: "p", x: "Put these to the manufacturer and the facade consultant early, before shop drawings are approved, when changes are still cheap." },
    { t: "ol", items: [
      "What wind load does the specification set, and where did it come from?",
      "Which standard method was used, and what pressures were applied?",
      "Which movement limits apply to the frame, the glass and the supporting structure?",
      "How closely does the tested sample match the project drawings?",
      "What is the plan for any part of the project that differs from the sample?",
      "Who witnessed the test, and how will the report be filed with the approved drawings?",
    ] },
    { t: "p", x: "Reading {{/journal/reading-facade-shop-drawings|facade shop drawings}} alongside the report is the quickest way to find mismatches, because the drawing shows the real spans, anchors and glass that the report must cover. For the system itself, see {{/systems/curtain-wall|curtain wall}}." },
    { t: "note", x: "This guidance is general. Design loads, test methods, pressures, movement limits and acceptance criteria are confirmed per project with the facade consultant and the relevant standards." },
  ],
};

export default article;
