import type { Article } from "../journal";

const article: Article = {
  slug: "terracotta-hpl-or-acp-cladding",
  title: "Terracotta, HPL or ACP cladding: choosing a facade skin",
  seoTitle: "Terracotta, HPL or ACP Cladding",
  description: "Terracotta, HPL and ACP all clad a rain-screen wall but behave differently. Compare look, weight, fixing, upkeep and the questions to settle first.",
  excerpt: "Three popular cladding skins can sit on the same rain-screen wall, yet each looks, ages and is fixed differently. Here is how to compare them before you commit.",
  teaser: "How terracotta, HPL and ACP differ in look, fixing and upkeep.",
  topic: "Cladding",
  date: "2026-10-08",
  hero: "terra-hero",
  card: "terra-card",
  og: "/og/cladding.jpg",
  terms: ["acp", "rain-screen", "cassette"],
  systems: ["cladding", "rain-screen-facade"],
  faq: [
    { question: "What is the difference between terracotta, HPL and ACP cladding?", answer: "Terracotta is fired clay, HPL is compressed resin-bonded laminate, and ACP is a pair of thin metal skins around a core. They can all form a rain-screen skin, but they differ in surface character, panel size, weight, fixing method and how they age outdoors." },
    { question: "Which cladding is best for an Indian climate?", answer: "No single material wins everywhere. Heat, monsoon rain, dust, pollution and coastal air all matter, as do building height and budget. Compare the finish warranty, the fixing system and the cavity design for your site, and ask the facade consultant to confirm the choice." },
    { question: "Is HPL cladding suitable for external walls?", answer: "Exterior-grade HPL is made for outdoor use, but only the grade stated by the manufacturer for external facades should be used. Check the surface protection, the fixing method and the fire requirements for your building with the supplier and consultant before ordering." },
    { question: "Can ACP, HPL and terracotta use the same support frame?", answer: "Sometimes the same type of aluminium sub-frame can carry different skins, but loads, panel sizes and fixing points differ. The sub-frame should be designed for the chosen material, so changing the skin late in a project needs a fresh review of drawings and anchors." },
  ],
  body: [
    { t: "p", x: "Most people choose a cladding skin by colour and photograph. That is a fair start, but the skin also decides how the wall is fixed, how it moves in heat, how it is cleaned and what happens when a panel is damaged. Terracotta, high-pressure laminate and aluminium composite panels can all produce a handsome {{rain-screen|rain-screen}} wall. They are not interchangeable once drawings begin. This article compares them in plain terms so the decision is made on purpose." },
    { t: "h2", x: "What each material actually is" },
    { t: "p", x: "Terracotta cladding is fired clay, shaped as a hollow panel or tile and finished with a natural or glazed surface. It is mineral, so its colour comes from the clay and the firing rather than from paint. High-pressure laminate, usually called HPL, is made from layers of paper or fibre bonded with resin under heat and pressure, with a decorative surface on the face. An {{acp|aluminium composite panel}} has two thin aluminium skins bonded to a core, and its finish is a coating applied to the metal." },
    { t: "p", x: "Each starts from a different logic. Clay is heavy, fired and mineral. Laminate is a dense board with a printed or pigmented face. A composite panel is a light metal sandwich that can be folded and routed. Those starting points explain most of what follows about weight, edges, fixing and ageing. The deeper comparison of two metal options is in {{/journal/acp-vs-solid-aluminium-cladding|ACP versus solid aluminium cladding}}." },
    { t: "h2", x: "Look and surface character" },
    { t: "p", x: "Terracotta has depth. The surface carries small variations that read as natural, and a long run of panels catches light in a soft, uneven way. That is often the reason an architect chooses it. HPL can imitate timber, stone or flat colour with great consistency, so it suits designs that want a crisp, controlled elevation. ACP gives the sharpest planes and can look almost like a single sheet of coloured metal, with a finish range that includes solid, metallic and mirror-like options." },
    { t: "p", x: "Ask each supplier how much variation between batches is normal and how it is controlled. Natural material will vary more, and that is part of its character. Printed or coated products should be much closer, but the finish still needs an agreed tolerance. Look at a large sample outdoors, in morning and evening light, beside the adjoining glass and frames, rather than approving a small chip under office lights." },
    { t: "h2", x: "Weight, panel size and the support frame" },
    { t: "p", x: "Weight drives the design of the sub-frame, the brackets and the anchors into the structure. Terracotta is the heaviest of the three, so its supporting rails and fixings need the most attention. HPL sits in the middle. ACP is the lightest and is often chosen where the structure or the budget prefers a lighter wall. A heavier skin is not a defect, but the support system has to be designed for it from the beginning." },
    { t: "p", x: "Panel size follows the material. Fired clay is limited by what can be made and handled without breaking, so it usually comes in a modular size. Laminate boards and composite sheets can be cut to larger formats, which reduces the number of joints but raises handling and wind questions. Confirm the maximum panel size and the allowed thickness with the supplier, then check the sub-frame spacing against it on the {{shop-drawings|shop drawings}}." },
    { t: "img", id: "terra-1", cap: "A rain-screen skin is only one layer of the wall: the support frame, cavity and fixings behind it do much of the work." },
    { t: "h2", x: "How each skin is fixed" },
    { t: "p", x: "Fixing method is where the three differ most in the field. Terracotta panels are commonly hung on horizontal rails, with clips that hold each panel and allow it to be replaced. HPL boards may be fixed with visible fasteners, concealed adhesive systems or clip systems, depending on the board and the look. ACP is often formed into a {{cassette|cassette}}, a shallow tray with folded edges that hangs on the sub-frame, or fixed as a flat bonded panel." },
    { t: "p", x: "Visible and concealed fixings give different appearances and different tolerances for movement. Whatever the choice, the fixing must be the one approved by the panel manufacturer for that product, not an improvised substitute. Ask how a single damaged panel is removed and replaced without disturbing its neighbours. A system that cannot be repaired panel by panel will make maintenance expensive later." },
    { t: "h2", x: "Cavity, drainage and movement" },
    { t: "p", x: "All three are normally used as an open-joint or closed-joint skin in front of a protected wall. Rain that gets past the skin should drain, and the {{ventilated-cavity|ventilated cavity}} behind should dry out. The skin is a first line of defence, not the waterproofing. Read {{/journal/rain-screen-cladding-the-gap|the gap behind rain-screen cladding}} to see why the cavity matters as much as the panel." },
    { t: "p", x: "Materials expand and contract at different rates, and clay, laminate and metal do not behave alike. Joints, slotted holes and clip tolerances must let each skin move without buckling or cracking. Metal tends to move more with temperature, while fired clay is dimensionally stable but brittle. Plan {{movement-joint|movement joints}} with the chosen skin in mind and do not assume a detail from one material works for another." },
    { t: "h2", x: "Durability, finish and upkeep" },
    { t: "p", x: "Terracotta does not rely on a surface coating, so it does not chalk or peel, though it can collect dirt and soiling in textured faces. HPL depends on its protective surface layer to resist sunlight and weather, so the exterior grade and its stated warranty matter. ACP depends on its coating, commonly a {{pvdf-coating|PVDF coating}}, and on the quality of the bond between skins and core. Ask for the finish warranty in writing and read what it excludes." },
    { t: "p", x: "Cleaning is straightforward for all three if done with methods the supplier approves. Avoid harsh solvents and abrasive tools, which can mark coatings and laminate faces. Coastal air, heavy pollution and dust change how often a wall needs washing. A short cleaning and inspection routine, written at handover, protects the appearance and the warranty. The wider routine is in the {{/journal/facade-maintenance-checklist|facade maintenance checklist}}." },
    { t: "h2", x: "Fire, code and approvals" },
    { t: "p", x: "Cladding is a fire-safety question as well as a design one. The core of a composite panel, the resin in a laminate and the backing, insulation and cavity barriers behind any skin all matter to how a wall behaves. Requirements depend on the building height, use and the local code. Never rely on a general statement that a material is acceptable. Ask for the documents the manufacturer gives for the exact product and the exact build-up proposed." },
    { t: "p", x: "The facade consultant and the approving authority decide what is acceptable for the project. Treat this as an early gate, not a late check. A skin chosen for its looks and then rejected at approval costs time and design work. Bring the fire strategy into the conversation when the shortlist is made, along with the {{/systems/cladding|cladding system}} options being considered." },
    { t: "h2", x: "Cost, lead time and site handling" },
    { t: "p", x: "Price should be compared on the installed wall, not on the panel alone. A heavier skin needs a stronger sub-frame and more fixings, a more complex panel needs more fabrication time, and a more delicate one needs more care on site. Ask each bidder to price the panel, the support frame, the fixings, the insulation and cavity barriers, and the access equipment as separate lines so the real difference is visible." },
    { t: "p", x: "Lead time deserves the same honesty. Fired clay is made in batches, laminate boards are cut from stock sizes, and composite panels are fabricated to order, so the delivery pattern is different for each. Confirm when the first panels will arrive and how a late or damaged batch is handled. On site, store panels flat or on edge as the maker advises, keep them dry, and protect faces until final cleaning." },
    { t: "h2", x: "A simple way to decide" },
    { t: "ol", items: [
      "Write down the look you want: natural variation, controlled colour, or sharp metal planes.",
      "Check the structure and budget for the weight the support frame must carry.",
      "Confirm the fixing system and how a single panel is replaced.",
      "Review the cavity, drainage and movement details with the facade consultant.",
      "Read the finish warranty and the fire documents for the exact product.",
      "Approve a large sample or a full-bay {{mock-up|mock-up}} before ordering.",
    ] },
    { t: "p", x: "If two materials remain close, compare them on maintenance and replacement rather than on first appearance. The wall will be looked at for years and repaired occasionally, and the easier it is to replace one panel, the better it will age. Send the drawings and finish intent to a manufacturer early, using the checklist in {{/journal/what-to-send-a-facade-manufacturer|what to send a facade manufacturer}}, so the sub-frame is designed for the skin you pick." },
    { t: "note", x: "This guidance is general. Material grades, fixing systems, fire requirements and warranties are confirmed per project with the facade consultant and the approved manufacturer." },
  ],
};

export default article;
