import type { Article } from "../journal";

const article: Article = {
  slug: "value-engineering-a-facade-without-losing-performance",
  title: "Value engineering a facade without losing performance",
  seoTitle: "Value Engineering a Facade",
  description: "How to cut facade cost without cutting performance: what is safe to change, what is not, and how to compare options on a like-for-like basis.",
  excerpt: "Value engineering can save money on a facade, or quietly remove the things the building needs. The difference is knowing which changes are safe and how to compare them.",
  teaser: "Which facade savings are safe, which are not, and how to compare.",
  topic: "Enquiries",
  date: "2026-10-08",
  hero: "ve-hero",
  card: "ve-card",
  og: "/og/cladding.jpg",
  terms: ["facade-consultant", "thermal-break", "mock-up"],
  systems: ["curtain-wall", "cladding"],
  faq: [
    {
      question: "What is value engineering in a facade project?",
      answer: "It is a structured review of the design to find the same function at lower cost, or better function at the same cost. Done well, it removes waste and simplifies details. Done badly, it removes performance that the building needs. The test is whether the requirement is still met.",
    },
    {
      question: "What can be changed safely to reduce facade cost?",
      answer: "Usually things that do not affect performance: repeating panel sizes, simplifying the module, reducing the number of different details, or choosing a standard finish. Changes to glass, thermal breaks, drainage, anchors or movement joints need engineering review, since they affect what the facade does.",
    },
    {
      question: "How do I compare two facade quotations fairly?",
      answer: "Compare the same scope, the same performance requirements and the same exclusions. List what each quote includes: glass build-up, finish, anchors, testing, scaffolding and warranty. A cheaper quote that omits items or lowers specification is not a like-for-like saving.",
    },
    {
      question: "Who should approve a change to the facade specification?",
      answer: "The change should be proposed in writing, reviewed by the facade consultant and approved by the architect and client before it is made. The review should state what changes, what it affects and what evidence shows the performance requirement is still met.",
    },
  ],
  body: [
    { t: "p", x: "At some point in most projects, the facade cost is higher than the budget. The usual response is a value engineering exercise: a review in which everyone looks for savings. The idea is sound. The risk is that a facade is a system in which small changes spread. A thinner section, a cheaper sealant or a smaller drainage path can look like a saving on paper and become a leak, a crack or a failed test after installation. This article sets out how to find real savings and how to avoid the false ones." },
    { t: "h2", x: "What value engineering is, and is not" },
    { t: "p", x: "Value engineering means keeping the function and reducing the cost. It is not the same as reducing the specification. If a cheaper product does the same job, that is value engineering. If it does less of the job, that is a downgrade, and it should be described as one, with the client's agreement." },
    { t: "p", x: "A useful rule is to write down the function first. What must this element do? Resist wind, keep water out, limit heat gain, last a stated period, look consistent. A proposed change is then judged against that list, not against the price alone. If nobody can say what function the item serves, ask before removing it." },
    { t: "p", x: "Timing matters as much as the idea. A change proposed at concept stage costs almost nothing to adopt, because only a drawing changes. The same change proposed after shop drawings are approved means redrawing, reordering and possibly retesting. If the budget is under pressure, start the review early and involve the manufacturer, who knows what is cheap to make and what is not." },
    { t: "p", x: "Be alert to the way savings are presented. A line that says 'equivalent' should be backed by evidence that the substitute does the same job, and not just by a brochure. Ask who carries the risk if it turns out not to. If the answer is vague, the saving is probably being paid for by the client." },
    { t: "h2", x: "Savings that are usually safe" },
    { t: "p", x: "Savings come most reliably from simplifying the design, not thinning the parts. The factory makes repeated things cheaply and varied things slowly. Reducing the variety in the facade lowers cost without touching performance." },
    { t: "ul", items: [
      "Repeat panel and glass sizes so fewer different units are made.",
      "Align the module with the structural grid and slab edges.",
      "Reduce the number of unique corners, returns and special junctions.",
      "Choose a standard profile series and finish range instead of a custom one.",
      "Simplify trims and feature elements that add little to the elevation.",
      "Rationalise access and hoisting so installation is quicker and safer.",
    ] },
    { t: "p", x: "These changes are worth pursuing early. Each one reduces fabrication, handling and installation time. They also reduce the number of details that need testing and checking." },
    { t: "img", id: "ve-1", cap: "Repeating one module across an elevation saves more than thinning any single part." },
    { t: "p", x: "There is a second class of safe saving: removing duplication between trades. Two contractors may each price the same flashing, the same scaffold or the same protection. Clear scope boundaries, agreed early, remove this waste without touching the facade itself. It is often the quickest saving to find and the least controversial to approve." },
    { t: "h2", x: "Savings that need engineering review" },
    { t: "p", x: "Some items look like cost but are performance. Changing them can still be valid, but only after a documented review by the {{facade-consultant|facade consultant}} and the manufacturer's engineers." },
    { t: "ul", items: [
      "Glass build-up: coatings, laminated layers and unit make-up decide heat, sound and safety.",
      "The {{thermal-break|thermal break}} in aluminium frames, which affects heat flow and condensation risk.",
      "Frame depth and wall thickness, which carry wind load and limit movement.",
      "Anchors and fixings, which carry the facade weight into the structure.",
      "Drainage paths and gaskets, which keep water out of the interior.",
      "Sealant type and joint size, which accommodate movement.",
    ] },
    { t: "p", x: "For instance, a thermal break that is removed or replaced with a smaller one can change condensation behaviour near the frame. Our article on {{/journal/thermal-breaks-in-aluminium-frames|thermal breaks in aluminium frames}} explains why. The effect might not be visible for months, which is exactly why the review is needed before the change." },
    { t: "p", x: "A good test for any item on the list is to ask what happens if it is wrong. If a joint is slightly too narrow, does the sealant tear in the first hot season? If an anchor is lighter, does the slab edge crack, or does the frame sag? Items with serious consequences deserve evidence, and items with trivial ones can be decided quickly." },
    { t: "h2", x: "Savings to be careful with" },
    { t: "p", x: "Some changes shift cost to another party or another year. A cheaper finish may need repainting sooner. A coating with a shorter life may need replacement within a maintenance cycle. A system that is easier to make but harder to replace a damaged pane in can cost more over the life of the building." },
    { t: "p", x: "Compare finishes honestly. Our guide to {{/journal/anodised-powder-coated-or-pvdf|anodised, powder-coated or PVDF finishes}} sets out the trade-offs, including how each behaves outdoors. Think in terms of the cost over the period the building will be owned, not only the cost on handover day." },
    { t: "p", x: "Cladding offers a good example. Choosing between panel materials changes weight, fixing, finish life and how the wall drains. Our comparison of {{/journal/acp-vs-solid-aluminium-cladding|ACP and solid aluminium cladding}} shows how a cheaper-looking panel can change the support structure and the maintenance plan. The panel price is only one line of the total." },
    { t: "p", x: "Programme is another hidden cost. A cheaper option that needs longer lead times or more site work can delay handover, and a delayed handover costs the client rent, interest or both. Count time as money when you compare options, and ask each bidder to state its lead times plainly." },
    { t: "h2", x: "Comparing options like for like" },
    { t: "p", x: "Once alternatives exist, compare them on one page. A table that lists each option against the same requirements prevents the cheapest-looking quote from winning on omissions. Include:" },
    { t: "ol", items: [
      "The performance requirements each option meets, with evidence.",
      "The glass build-up, finish, anchors and sealants included.",
      "What is excluded, such as access equipment, scaffolding and site testing.",
      "The tests, certificates and reports offered.",
      "The warranty terms and maintenance requirements.",
      "The effect on the programme, including lead times for special items.",
    ] },
    { t: "p", x: "Where a claim cannot be supported by a report or calculation, treat it as unproven. Ask for the document, not a verbal assurance." },
    { t: "p", x: "Ask one more question of every proposal: who benefits? Sometimes a saving belongs to the contractor and the performance loss belongs to the owner. A fair proposal shares the benefit, for instance by passing on a reduction in price when a simpler detail is accepted, and states plainly what the owner gives up in exchange." },
    { t: "p", x: "Involve the people who will use and maintain the building. A facade manager can tell you which details have caused trouble before, and which finishes were hard to keep clean. That experience is free, and it often points to savings in upkeep that a price-only review would miss." },
    { t: "h2", x: "Test changes before you commit" },
    { t: "p", x: "When a change affects how the facade performs, check it before the whole building is made. A revised detail can be reviewed in a calculation, tested on a laboratory sample or built in a {{mock-up|mock-up}}. A mock-up is particularly useful when the change affects appearance, such as a different finish, a revised joint or a changed glass." },
    { t: "p", x: "Leave enough time in the programme. A late change that skips the mock-up saves a few weeks on paper and risks months if it fails. Our guide on {{/journal/facade-mock-up-review|reviewing a facade mock-up}} describes what to check. Also compare the proposed change against the testing described on our {{/testing|testing page}}, so it does not invalidate evidence you already hold." },
    { t: "p", x: "Agree a cut-off date for changes. After a certain point, such as shop drawing approval, every change should require formal review and an honest statement of its cost and programme effect. Without a cut-off, small late changes pile up, and each one seems harmless until the programme is gone." },
    { t: "h2", x: "Record every change" },
    { t: "p", x: "Each accepted change should be written down: what was changed, why, who approved it, and what evidence shows the requirement is still met. Update the drawings and the specification so that the installed facade, the paperwork and the maintenance manual all describe the same thing." },
    { t: "p", x: "Without this record, a building owner may discover years later that a performance requirement was dropped, with no one able to say who agreed. A clear trail protects the client, the designer and the manufacturer. For wall systems that may be affected, see {{/systems/curtain-wall|curtain wall}} and {{/systems/cladding|cladding}}." },
    { t: "note", x: "This guidance is general. Which changes are acceptable, and the values and standards that apply, are confirmed per project with the facade consultant." },
  ],
};

export default article;
