import type { Article } from "../journal";

const article: Article = {
  slug: "window-drainage-and-weep-holes",
  title: "Window drainage and weep holes: where rain goes",
  seoTitle: "Window Drainage and Weep Holes",
  description: "Follow rain through a drained aluminium window: outer seals, glazing pockets, sill tracks, weep outlets and the wall interface.",
  excerpt: "Some water can reach a window's outer chambers. A sound design manages it and sends it back outside without crossing the interior seal.",
  teaser: "Follow the water before sealing a suspected leak.",
  topic: "Windows & doors",
  date: "2026-10-07",
  hero: "casement-hero",
  card: "casement-card",
  og: "/og/sliding-windows-doors.jpg",
  terms: ["drainage-slot", "gasket"],
  systems: ["casement-windows", "sliding-windows-doors"],
  faq: [
    { question: "Should a window frame have holes to the outside?", answer: "Many drained systems have designed outlets that let incidental water escape. Their size and position come from the approved profile system; an installer should not block them or drill new ones without an engineered detail." },
    { question: "Can I seal a weep hole to stop water?", answer: "No. Blocking an intended outlet can trap water and increase the chance of an interior leak. Diagnose the source and designed drainage path first." },
    { question: "Why does a window leak only in wind-driven rain?", answer: "Wind changes pressure and can drive more water across seals and joints. The cause may be a blocked drain, poor gasket, perimeter interface or another detail; inspect and test the complete installation under an agreed method." },
  ],
  body: [
    { t: "p", x: "A window can appear tightly closed and still contain a designed water path. Many aluminium systems expect a small amount of rain to pass an outer line of defence into a controlled chamber, then drain back outdoors. The interior air and water line must remain protected. This is why a visible opening near a sill is not automatically a defect. Understanding the route is useful both when choosing a window and when investigating a leak. Sealing a drain by instinct can make the problem worse." },
    { t: "h2", x: "Trace water from the glass to the outside" },
    { t: "p", x: "Rain meets glass, glazing gaskets, frame joints and opening-leaf seals. Most is shed away; incidental water that enters a glazing pocket or sill channel should reach a drainage chamber and leave through designed {{drainage-slot|drainage slots}} or weep openings. The exact arrangement varies by system. Ask the supplier for a section showing the outer path, internal baffles, the protected inner seal and the exit. A section with a generic arrow labelled 'drainage' is less useful than one that shows actual openings and levels." },
    { t: "p", x: "The sill should have a clear route outward even after the frame is installed in a wall. A projecting stone sill, tile, sealant bead or cladding return must not cover the outlets. The perimeter interface also needs a path for water that reaches the installation gap. Coordinate it with the wall's drainage plane and flashing strategy. A window may drain perfectly in a laboratory sample and still leak when an on-site sill or trim directs water back under the frame." },
    { t: "h2", x: "Pressure changes the behaviour" },
    { t: "p", x: "Wind creates pressure differences across the facade. Water can be pushed through a small outer gap, and a poorly protected outlet can become an entry point. Some systems use baffled openings and pressure equalisation to manage those forces. The key is continuity: a chamber designed to drain and ventilate should not accidentally connect to the room. Check corners, screw penetrations and meeting stiles as well as the straight profile section. Those discontinuities often decide real performance." },
    { t: "p", x: "A sliding window has a long track that can collect water and dust. A casement uses compression seals but still needs its glazing pocket and sill managed. Neither type should be chosen by an assumption that one can never leak. Compare complete assemblies tested under the project's required conditions, and examine details for the chosen size and configuration. A test of a small fixed window does not describe a large sliding balcony door." },
    { t: "img", id: "casement-1", cap: "The visible window type does not show the drainage chambers and protected inner seal inside its frame." },
    { t: "h2", x: "Separate a blocked drain from a failed joint" },
    { t: "p", x: "When water appears inside, record weather, wind direction, the affected room and where the first drop emerged. Check for dirt, leaves, construction debris or paint in sill tracks and outlets. Cleaning may solve a simple blockage, but a large recurring flow deserves a wider inspection. A missing gasket, poorly sealed corner, badly formed perimeter joint or water arriving from the wall above can all produce the same stain near a sill." },
    { t: "p", x: "Do not add sealant until the designed route is understood. A bead across the wrong gap can block ventilation or drainage, trap water against an insulated glass edge, or simply move the leak elsewhere. Compare the installation with the approved shop drawing and inspect the wall interface. A controlled field water check, selected by the facade consultant, may help isolate the entry point. Document the original condition and any repair before retesting." },
    { t: "h2", x: "Design and installation checks" },
    { t: "p", x: "At drawing review, trace the water line through each corner, transom and sill. Confirm outlet positions, the route through a coupled window or door, and the connection to flashing. At fabrication, keep machined slots open and consistent with the profile supplier's instructions. During installation, verify frame level and outward fall where required by the system. Protect tracks from mortar, grinding dust and temporary tape residue. Inspect the first completed unit before repeating the same detail across a building." },
    { t: "p", x: "Maintenance is part of the design. Occupants should know that drainage openings need to remain clear, but cleaning instructions should avoid dismantling seals or probing concealed chambers with sharp tools. Facilities teams can check representative units after monsoon storms and log repeated issues by elevation. If several units on the same side leak, investigate the shared detail and wind exposure rather than repeatedly patching individual sills." },
    { t: "h2", x: "Keep the inner line dry" },
    { t: "p", x: "The aim is not to pretend that no rain can ever reach an outer chamber. It is to maintain a reliable path back outside and a continuous protected line toward the room. Ask for drawings and tests that show the whole installed condition, including its wall connection. When a leak occurs, trace the route before changing it. That approach is slower than reaching for sealant on the first visit, but more likely to solve the actual problem." },
    { t: "h2", x: "What to ask at a sample window" },
    { t: "p", x: "Before a large order, inspect one assembled window or door. Ask the fabricator to show the glazing pocket, sill chamber and outdoor outlet on a real section. Check whether each corner joint preserves that route and whether a setting block could obstruct it. If the unit couples to another frame, follow water through the connector rather than stopping at the first member. An installer should be able to point to the inner air seal and explain why water cannot cross it under the conditions defined for the system." },
    { t: "p", x: "Compare the sample with the intended wall opening. Where will flashing sit? Can the sill be cleaned after internal finishes and external cladding are fitted? Does a stone projection splash water toward the outlet? Will a balcony surface create standing water against a threshold? These questions sit between window supplier, facade installer and architect. A good sample includes enough of the surrounding wall to answer them, not just a freestanding frame on a factory bench." },
    { t: "h2", x: "Handle maintenance and leaks methodically" },
    { t: "p", x: "Facilities staff can keep accessible tracks clear of dust, leaves and packaging fragments with cleaning methods approved by the supplier. They should not enlarge a weep hole or remove a concealed baffle. If a water complaint occurs, note the first wet point and check for a simple blockage before invasive work. A specialist can then compare the as-built unit with its drawing, inspect the weather-side and room-side seals, and choose an appropriate controlled water test if the cause remains uncertain." },
    { t: "p", x: "After repair, check the same bay in the conditions that previously produced the problem where practical. Keep a photograph of the repaired detail and record whether the cause was a blocked route, a fabrication joint, a perimeter interface or another building element. A pattern across many windows may point to a repeated manufacturing or installation issue. The aim is to preserve a working drainage design over years of use, not to make every visible opening disappear behind sealant." },
    { t: "note", x: "Drainage layouts are system-specific. Follow the approved supplier detail and project test requirements; do not drill, block or reseal outlets without a reviewed repair method." },
  ],
};

export default article;
